"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.net.address_pb2
import common.net.port_pb2
import common.serial.typed_message_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import transport.internet.config_pb2
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class InboundConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___InboundConfig = InboundConfig

@typing.final
class AllocationStrategy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AllocationStrategy._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Always: AllocationStrategy._Type.ValueType  # 0
        """Always allocate all connection handlers."""
        Random: AllocationStrategy._Type.ValueType  # 1
        """Randomly allocate specific range of handlers."""
        External: AllocationStrategy._Type.ValueType  # 2
        """External. Not supported yet."""

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    Always: AllocationStrategy.Type.ValueType  # 0
    """Always allocate all connection handlers."""
    Random: AllocationStrategy.Type.ValueType  # 1
    """Randomly allocate specific range of handlers."""
    External: AllocationStrategy.Type.ValueType  # 2
    """External. Not supported yet."""

    @typing.final
    class AllocationStrategyConcurrency(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        VALUE_FIELD_NUMBER: builtins.int
        value: builtins.int
        def __init__(
            self,
            *,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

    @typing.final
    class AllocationStrategyRefresh(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        VALUE_FIELD_NUMBER: builtins.int
        value: builtins.int
        def __init__(
            self,
            *,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    CONCURRENCY_FIELD_NUMBER: builtins.int
    REFRESH_FIELD_NUMBER: builtins.int
    type: global___AllocationStrategy.Type.ValueType
    @property
    def concurrency(self) -> global___AllocationStrategy.AllocationStrategyConcurrency:
        """Number of handlers (ports) running in parallel.
        Default value is 3 if unset.
        """

    @property
    def refresh(self) -> global___AllocationStrategy.AllocationStrategyRefresh:
        """Number of minutes before a handler is regenerated.
        Default value is 5 if unset.
        """

    def __init__(
        self,
        *,
        type: global___AllocationStrategy.Type.ValueType = ...,
        concurrency: global___AllocationStrategy.AllocationStrategyConcurrency | None = ...,
        refresh: global___AllocationStrategy.AllocationStrategyRefresh | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["concurrency", b"concurrency", "refresh", b"refresh"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["concurrency", b"concurrency", "refresh", b"refresh", "type", b"type"]) -> None: ...

global___AllocationStrategy = AllocationStrategy

@typing.final
class SniffingConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    DESTINATION_OVERRIDE_FIELD_NUMBER: builtins.int
    DOMAINS_EXCLUDED_FIELD_NUMBER: builtins.int
    METADATA_ONLY_FIELD_NUMBER: builtins.int
    ROUTE_ONLY_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    """Whether or not to enable content sniffing on an inbound connection."""
    metadata_only: builtins.bool
    """Whether should only try to sniff metadata without waiting for client input.
    Can be used to support SMTP like protocol where server send the first
    message.
    """
    route_only: builtins.bool
    @property
    def destination_override(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Override target destination if sniff'ed protocol is in the given list.
        Supported values are "http", "tls", "fakedns".
        """

    @property
    def domains_excluded(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        enabled: builtins.bool = ...,
        destination_override: collections.abc.Iterable[builtins.str] | None = ...,
        domains_excluded: collections.abc.Iterable[builtins.str] | None = ...,
        metadata_only: builtins.bool = ...,
        route_only: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["destination_override", b"destination_override", "domains_excluded", b"domains_excluded", "enabled", b"enabled", "metadata_only", b"metadata_only", "route_only", b"route_only"]) -> None: ...

global___SniffingConfig = SniffingConfig

@typing.final
class ReceiverConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PORT_LIST_FIELD_NUMBER: builtins.int
    LISTEN_FIELD_NUMBER: builtins.int
    ALLOCATION_STRATEGY_FIELD_NUMBER: builtins.int
    STREAM_SETTINGS_FIELD_NUMBER: builtins.int
    RECEIVE_ORIGINAL_DESTINATION_FIELD_NUMBER: builtins.int
    SNIFFING_SETTINGS_FIELD_NUMBER: builtins.int
    receive_original_destination: builtins.bool
    @property
    def port_list(self) -> common.net.port_pb2.PortList:
        """PortList specifies the ports which the Receiver should listen on."""

    @property
    def listen(self) -> common.net.address_pb2.IPOrDomain:
        """Listen specifies the IP address that the Receiver should listen on."""

    @property
    def allocation_strategy(self) -> global___AllocationStrategy: ...
    @property
    def stream_settings(self) -> transport.internet.config_pb2.StreamConfig: ...
    @property
    def sniffing_settings(self) -> global___SniffingConfig: ...
    def __init__(
        self,
        *,
        port_list: common.net.port_pb2.PortList | None = ...,
        listen: common.net.address_pb2.IPOrDomain | None = ...,
        allocation_strategy: global___AllocationStrategy | None = ...,
        stream_settings: transport.internet.config_pb2.StreamConfig | None = ...,
        receive_original_destination: builtins.bool = ...,
        sniffing_settings: global___SniffingConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["allocation_strategy", b"allocation_strategy", "listen", b"listen", "port_list", b"port_list", "sniffing_settings", b"sniffing_settings", "stream_settings", b"stream_settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["allocation_strategy", b"allocation_strategy", "listen", b"listen", "port_list", b"port_list", "receive_original_destination", b"receive_original_destination", "sniffing_settings", b"sniffing_settings", "stream_settings", b"stream_settings"]) -> None: ...

global___ReceiverConfig = ReceiverConfig

@typing.final
class InboundHandlerConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    RECEIVER_SETTINGS_FIELD_NUMBER: builtins.int
    PROXY_SETTINGS_FIELD_NUMBER: builtins.int
    tag: builtins.str
    @property
    def receiver_settings(self) -> common.serial.typed_message_pb2.TypedMessage: ...
    @property
    def proxy_settings(self) -> common.serial.typed_message_pb2.TypedMessage: ...
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        receiver_settings: common.serial.typed_message_pb2.TypedMessage | None = ...,
        proxy_settings: common.serial.typed_message_pb2.TypedMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["proxy_settings", b"proxy_settings", "receiver_settings", b"receiver_settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["proxy_settings", b"proxy_settings", "receiver_settings", b"receiver_settings", "tag", b"tag"]) -> None: ...

global___InboundHandlerConfig = InboundHandlerConfig

@typing.final
class OutboundConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___OutboundConfig = OutboundConfig

@typing.final
class SenderConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VIA_FIELD_NUMBER: builtins.int
    STREAM_SETTINGS_FIELD_NUMBER: builtins.int
    PROXY_SETTINGS_FIELD_NUMBER: builtins.int
    MULTIPLEX_SETTINGS_FIELD_NUMBER: builtins.int
    VIA_CIDR_FIELD_NUMBER: builtins.int
    TARGET_STRATEGY_FIELD_NUMBER: builtins.int
    via_cidr: builtins.str
    target_strategy: transport.internet.config_pb2.DomainStrategy.ValueType
    @property
    def via(self) -> common.net.address_pb2.IPOrDomain:
        """Send traffic through the given IP. Only IP is allowed."""

    @property
    def stream_settings(self) -> transport.internet.config_pb2.StreamConfig: ...
    @property
    def proxy_settings(self) -> transport.internet.config_pb2.ProxyConfig: ...
    @property
    def multiplex_settings(self) -> global___MultiplexingConfig: ...
    def __init__(
        self,
        *,
        via: common.net.address_pb2.IPOrDomain | None = ...,
        stream_settings: transport.internet.config_pb2.StreamConfig | None = ...,
        proxy_settings: transport.internet.config_pb2.ProxyConfig | None = ...,
        multiplex_settings: global___MultiplexingConfig | None = ...,
        via_cidr: builtins.str = ...,
        target_strategy: transport.internet.config_pb2.DomainStrategy.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["multiplex_settings", b"multiplex_settings", "proxy_settings", b"proxy_settings", "stream_settings", b"stream_settings", "via", b"via"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["multiplex_settings", b"multiplex_settings", "proxy_settings", b"proxy_settings", "stream_settings", b"stream_settings", "target_strategy", b"target_strategy", "via", b"via", "via_cidr", b"via_cidr"]) -> None: ...

global___SenderConfig = SenderConfig

@typing.final
class MultiplexingConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    CONCURRENCY_FIELD_NUMBER: builtins.int
    XUDPCONCURRENCY_FIELD_NUMBER: builtins.int
    XUDPPROXYUDP443_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    """Whether or not Mux is enabled."""
    concurrency: builtins.int
    """Max number of concurrent connections that one Mux connection can handle."""
    xudpConcurrency: builtins.int
    """Transport XUDP in another Mux."""
    xudpProxyUDP443: builtins.str
    """"reject" (default), "allow" or "skip"."""
    def __init__(
        self,
        *,
        enabled: builtins.bool = ...,
        concurrency: builtins.int = ...,
        xudpConcurrency: builtins.int = ...,
        xudpProxyUDP443: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["concurrency", b"concurrency", "enabled", b"enabled", "xudpConcurrency", b"xudpConcurrency", "xudpProxyUDP443", b"xudpProxyUDP443"]) -> None: ...

global___MultiplexingConfig = MultiplexingConfig
