"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Severity:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SeverityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Severity.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Unknown: _Severity.ValueType  # 0
    Error: _Severity.ValueType  # 1
    Warning: _Severity.ValueType  # 2
    Info: _Severity.ValueType  # 3
    Debug: _Severity.ValueType  # 4

class Severity(_Severity, metaclass=_SeverityEnumTypeWrapper): ...

Unknown: Severity.ValueType  # 0
Error: Severity.ValueType  # 1
Warning: Severity.ValueType  # 2
Info: Severity.ValueType  # 3
Debug: Severity.ValueType  # 4
global___Severity = Severity
