"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.protocol.server_spec_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VNEXT_FIELD_NUMBER: builtins.int
    @property
    def vnext(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.protocol.server_spec_pb2.ServerEndpoint]: ...
    def __init__(
        self,
        *,
        vnext: collections.abc.Iterable[common.protocol.server_spec_pb2.ServerEndpoint] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vnext", b"vnext"]) -> None: ...

global___Config = Config
