"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBJECT_SELECTOR_FIELD_NUMBER: builtins.int
    PING_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def subject_selector(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """@Document The selectors for outbound under observation"""

    @property
    def ping_config(self) -> global___HealthPingConfig: ...
    def __init__(
        self,
        *,
        subject_selector: collections.abc.Iterable[builtins.str] | None = ...,
        ping_config: global___HealthPingConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ping_config", b"ping_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ping_config", b"ping_config", "subject_selector", b"subject_selector"]) -> None: ...

global___Config = Config

@typing.final
class HealthPingConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DESTINATION_FIELD_NUMBER: builtins.int
    CONNECTIVITY_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    SAMPLINGCOUNT_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    HTTPMETHOD_FIELD_NUMBER: builtins.int
    destination: builtins.str
    """destination url, need 204 for success return
    default https://connectivitycheck.gstatic.com/generate_204
    """
    connectivity: builtins.str
    """connectivity check url"""
    interval: builtins.int
    """health check interval, int64 values of time.Duration"""
    samplingCount: builtins.int
    """sampling count is the amount of recent ping results which are kept for calculation"""
    timeout: builtins.int
    """ping timeout, int64 values of time.Duration"""
    httpMethod: builtins.str
    """http method to make request"""
    def __init__(
        self,
        *,
        destination: builtins.str = ...,
        connectivity: builtins.str = ...,
        interval: builtins.int = ...,
        samplingCount: builtins.int = ...,
        timeout: builtins.int = ...,
        httpMethod: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["connectivity", b"connectivity", "destination", b"destination", "httpMethod", b"httpMethod", "interval", b"interval", "samplingCount", b"samplingCount", "timeout", b"timeout"]) -> None: ...

global___HealthPingConfig = HealthPingConfig
