"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.protocol.user_pb2
import common.serial.typed_message_pb2
import core.config_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AddUserOperation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_FIELD_NUMBER: builtins.int
    @property
    def user(self) -> common.protocol.user_pb2.User: ...
    def __init__(
        self,
        *,
        user: common.protocol.user_pb2.User | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["user", b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["user", b"user"]) -> None: ...

global___AddUserOperation = AddUserOperation

@typing.final
class RemoveUserOperation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    email: builtins.str
    def __init__(
        self,
        *,
        email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email"]) -> None: ...

global___RemoveUserOperation = RemoveUserOperation

@typing.final
class AddInboundRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INBOUND_FIELD_NUMBER: builtins.int
    @property
    def inbound(self) -> core.config_pb2.InboundHandlerConfig: ...
    def __init__(
        self,
        *,
        inbound: core.config_pb2.InboundHandlerConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["inbound", b"inbound"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["inbound", b"inbound"]) -> None: ...

global___AddInboundRequest = AddInboundRequest

@typing.final
class AddInboundResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AddInboundResponse = AddInboundResponse

@typing.final
class RemoveInboundRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    tag: builtins.str
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["tag", b"tag"]) -> None: ...

global___RemoveInboundRequest = RemoveInboundRequest

@typing.final
class RemoveInboundResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RemoveInboundResponse = RemoveInboundResponse

@typing.final
class AlterInboundRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    OPERATION_FIELD_NUMBER: builtins.int
    tag: builtins.str
    @property
    def operation(self) -> common.serial.typed_message_pb2.TypedMessage: ...
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        operation: common.serial.typed_message_pb2.TypedMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["operation", b"operation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["operation", b"operation", "tag", b"tag"]) -> None: ...

global___AlterInboundRequest = AlterInboundRequest

@typing.final
class AlterInboundResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AlterInboundResponse = AlterInboundResponse

@typing.final
class ListInboundsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISONLYTAGS_FIELD_NUMBER: builtins.int
    isOnlyTags: builtins.bool
    def __init__(
        self,
        *,
        isOnlyTags: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["isOnlyTags", b"isOnlyTags"]) -> None: ...

global___ListInboundsRequest = ListInboundsRequest

@typing.final
class ListInboundsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INBOUNDS_FIELD_NUMBER: builtins.int
    @property
    def inbounds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[core.config_pb2.InboundHandlerConfig]: ...
    def __init__(
        self,
        *,
        inbounds: collections.abc.Iterable[core.config_pb2.InboundHandlerConfig] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["inbounds", b"inbounds"]) -> None: ...

global___ListInboundsResponse = ListInboundsResponse

@typing.final
class GetInboundUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    tag: builtins.str
    email: builtins.str
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "tag", b"tag"]) -> None: ...

global___GetInboundUserRequest = GetInboundUserRequest

@typing.final
class GetInboundUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERS_FIELD_NUMBER: builtins.int
    @property
    def users(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.protocol.user_pb2.User]: ...
    def __init__(
        self,
        *,
        users: collections.abc.Iterable[common.protocol.user_pb2.User] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["users", b"users"]) -> None: ...

global___GetInboundUserResponse = GetInboundUserResponse

@typing.final
class GetInboundUsersCountResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COUNT_FIELD_NUMBER: builtins.int
    count: builtins.int
    def __init__(
        self,
        *,
        count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["count", b"count"]) -> None: ...

global___GetInboundUsersCountResponse = GetInboundUsersCountResponse

@typing.final
class AddOutboundRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUTBOUND_FIELD_NUMBER: builtins.int
    @property
    def outbound(self) -> core.config_pb2.OutboundHandlerConfig: ...
    def __init__(
        self,
        *,
        outbound: core.config_pb2.OutboundHandlerConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["outbound", b"outbound"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["outbound", b"outbound"]) -> None: ...

global___AddOutboundRequest = AddOutboundRequest

@typing.final
class AddOutboundResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AddOutboundResponse = AddOutboundResponse

@typing.final
class RemoveOutboundRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    tag: builtins.str
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["tag", b"tag"]) -> None: ...

global___RemoveOutboundRequest = RemoveOutboundRequest

@typing.final
class RemoveOutboundResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RemoveOutboundResponse = RemoveOutboundResponse

@typing.final
class AlterOutboundRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    OPERATION_FIELD_NUMBER: builtins.int
    tag: builtins.str
    @property
    def operation(self) -> common.serial.typed_message_pb2.TypedMessage: ...
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        operation: common.serial.typed_message_pb2.TypedMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["operation", b"operation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["operation", b"operation", "tag", b"tag"]) -> None: ...

global___AlterOutboundRequest = AlterOutboundRequest

@typing.final
class AlterOutboundResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AlterOutboundResponse = AlterOutboundResponse

@typing.final
class ListOutboundsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListOutboundsRequest = ListOutboundsRequest

@typing.final
class ListOutboundsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUTBOUNDS_FIELD_NUMBER: builtins.int
    @property
    def outbounds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[core.config_pb2.OutboundHandlerConfig]: ...
    def __init__(
        self,
        *,
        outbounds: collections.abc.Iterable[core.config_pb2.OutboundHandlerConfig] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["outbounds", b"outbounds"]) -> None: ...

global___ListOutboundsResponse = ListOutboundsResponse

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Config = Config
