"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class IPOrDomain(google.protobuf.message.Message):
    """Address of a network host. It may be either an IP address or a domain
    address.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IP_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    ip: builtins.bytes
    """IP address. Must by either 4 or 16 bytes."""
    domain: builtins.str
    """Domain address."""
    def __init__(
        self,
        *,
        ip: builtins.bytes = ...,
        domain: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address", "domain", b"domain", "ip", b"ip"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "domain", b"domain", "ip", b"ip"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["address", b"address"]) -> typing.Literal["ip", "domain"] | None: ...

global___IPOrDomain = IPOrDomain
