"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import common.net.address_pb2
import common.net.network_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Endpoint(google.protobuf.message.Message):
    """Endpoint of a network connection."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NETWORK_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    network: common.net.network_pb2.Network.ValueType
    port: builtins.int
    @property
    def address(self) -> common.net.address_pb2.IPOrDomain: ...
    def __init__(
        self,
        *,
        network: common.net.network_pb2.Network.ValueType = ...,
        address: common.net.address_pb2.IPOrDomain | None = ...,
        port: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "network", b"network", "port", b"port"]) -> None: ...

global___Endpoint = Endpoint
