"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Network:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _NetworkEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Network.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Unknown: _Network.ValueType  # 0
    TCP: _Network.ValueType  # 2
    UDP: _Network.ValueType  # 3
    UNIX: _Network.ValueType  # 4

class Network(_Network, metaclass=_NetworkEnumTypeWrapper): ...

Unknown: Network.ValueType  # 0
TCP: Network.ValueType  # 2
UDP: Network.ValueType  # 3
UNIX: Network.ValueType  # 4
global___Network = Network

@typing.final
class NetworkList(google.protobuf.message.Message):
    """NetworkList is a list of Networks."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NETWORK_FIELD_NUMBER: builtins.int
    @property
    def network(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___Network.ValueType]: ...
    def __init__(
        self,
        *,
        network: collections.abc.Iterable[global___Network.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["network", b"network"]) -> None: ...

global___NetworkList = NetworkList
