"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PortRange(google.protobuf.message.Message):
    """PortRange represents a range of ports."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROM_FIELD_NUMBER: builtins.int
    TO_FIELD_NUMBER: builtins.int
    From: builtins.int
    """The port that this range starts from."""
    To: builtins.int
    """The port that this range ends with (inclusive)."""
    def __init__(
        self,
        *,
        From: builtins.int = ...,
        To: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["From", b"From", "To", b"To"]) -> None: ...

global___PortRange = PortRange

@typing.final
class PortList(google.protobuf.message.Message):
    """PortList is a list of ports."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RANGE_FIELD_NUMBER: builtins.int
    @property
    def range(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PortRange]: ...
    def __init__(
        self,
        *,
        range: collections.abc.Iterable[global___PortRange] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["range", b"range"]) -> None: ...

global___PortList = PortList
