"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.net.address_pb2
import common.protocol.server_spec_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _AuthType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AuthTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AuthType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NO_AUTH: _AuthType.ValueType  # 0
    """NO_AUTH is for anonymous authentication."""
    PASSWORD: _AuthType.ValueType  # 1
    """PASSWORD is for username/password authentication."""

class AuthType(_AuthType, metaclass=_AuthTypeEnumTypeWrapper):
    """AuthType is the authentication type of Socks proxy."""

NO_AUTH: AuthType.ValueType  # 0
"""NO_AUTH is for anonymous authentication."""
PASSWORD: AuthType.ValueType  # 1
"""PASSWORD is for username/password authentication."""
global___AuthType = AuthType

@typing.final
class Account(google.protobuf.message.Message):
    """Account represents a Socks account."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["password", b"password", "username", b"username"]) -> None: ...

global___Account = Account

@typing.final
class ServerConfig(google.protobuf.message.Message):
    """ServerConfig is the protobuf config for Socks server."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class AccountsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    AUTH_TYPE_FIELD_NUMBER: builtins.int
    ACCOUNTS_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    UDP_ENABLED_FIELD_NUMBER: builtins.int
    USER_LEVEL_FIELD_NUMBER: builtins.int
    auth_type: global___AuthType.ValueType
    udp_enabled: builtins.bool
    user_level: builtins.int
    @property
    def accounts(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def address(self) -> common.net.address_pb2.IPOrDomain: ...
    def __init__(
        self,
        *,
        auth_type: global___AuthType.ValueType = ...,
        accounts: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        address: common.net.address_pb2.IPOrDomain | None = ...,
        udp_enabled: builtins.bool = ...,
        user_level: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["accounts", b"accounts", "address", b"address", "auth_type", b"auth_type", "udp_enabled", b"udp_enabled", "user_level", b"user_level"]) -> None: ...

global___ServerConfig = ServerConfig

@typing.final
class ClientConfig(google.protobuf.message.Message):
    """ClientConfig is the protobuf config for Socks client."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_FIELD_NUMBER: builtins.int
    @property
    def server(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.protocol.server_spec_pb2.ServerEndpoint]:
        """Sever is a list of Socks server addresses."""

    def __init__(
        self,
        *,
        server: collections.abc.Iterable[common.protocol.server_spec_pb2.ServerEndpoint] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["server", b"server"]) -> None: ...

global___ClientConfig = ClientConfig
