"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import transport.internet.config_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RangeConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROM_FIELD_NUMBER: builtins.int
    TO_FIELD_NUMBER: builtins.int
    to: builtins.int
    def __init__(
        self,
        *,
        to: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["from", b"from", "to", b"to"]) -> None: ...

global___RangeConfig = RangeConfig

@typing.final
class XmuxConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAXCONCURRENCY_FIELD_NUMBER: builtins.int
    MAXCONNECTIONS_FIELD_NUMBER: builtins.int
    CMAXREUSETIMES_FIELD_NUMBER: builtins.int
    HMAXREQUESTTIMES_FIELD_NUMBER: builtins.int
    HMAXREUSABLESECS_FIELD_NUMBER: builtins.int
    HKEEPALIVEPERIOD_FIELD_NUMBER: builtins.int
    hKeepAlivePeriod: builtins.int
    @property
    def maxConcurrency(self) -> global___RangeConfig: ...
    @property
    def maxConnections(self) -> global___RangeConfig: ...
    @property
    def cMaxReuseTimes(self) -> global___RangeConfig: ...
    @property
    def hMaxRequestTimes(self) -> global___RangeConfig: ...
    @property
    def hMaxReusableSecs(self) -> global___RangeConfig: ...
    def __init__(
        self,
        *,
        maxConcurrency: global___RangeConfig | None = ...,
        maxConnections: global___RangeConfig | None = ...,
        cMaxReuseTimes: global___RangeConfig | None = ...,
        hMaxRequestTimes: global___RangeConfig | None = ...,
        hMaxReusableSecs: global___RangeConfig | None = ...,
        hKeepAlivePeriod: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cMaxReuseTimes", b"cMaxReuseTimes", "hMaxRequestTimes", b"hMaxRequestTimes", "hMaxReusableSecs", b"hMaxReusableSecs", "maxConcurrency", b"maxConcurrency", "maxConnections", b"maxConnections"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cMaxReuseTimes", b"cMaxReuseTimes", "hKeepAlivePeriod", b"hKeepAlivePeriod", "hMaxRequestTimes", b"hMaxRequestTimes", "hMaxReusableSecs", b"hMaxReusableSecs", "maxConcurrency", b"maxConcurrency", "maxConnections", b"maxConnections"]) -> None: ...

global___XmuxConfig = XmuxConfig

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class HeadersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    HOST_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    HEADERS_FIELD_NUMBER: builtins.int
    XPADDINGBYTES_FIELD_NUMBER: builtins.int
    NOGRPCHEADER_FIELD_NUMBER: builtins.int
    NOSSEHEADER_FIELD_NUMBER: builtins.int
    SCMAXEACHPOSTBYTES_FIELD_NUMBER: builtins.int
    SCMINPOSTSINTERVALMS_FIELD_NUMBER: builtins.int
    SCMAXBUFFEREDPOSTS_FIELD_NUMBER: builtins.int
    SCSTREAMUPSERVERSECS_FIELD_NUMBER: builtins.int
    XMUX_FIELD_NUMBER: builtins.int
    DOWNLOADSETTINGS_FIELD_NUMBER: builtins.int
    host: builtins.str
    path: builtins.str
    mode: builtins.str
    noGRPCHeader: builtins.bool
    noSSEHeader: builtins.bool
    scMaxBufferedPosts: builtins.int
    @property
    def headers(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def xPaddingBytes(self) -> global___RangeConfig: ...
    @property
    def scMaxEachPostBytes(self) -> global___RangeConfig: ...
    @property
    def scMinPostsIntervalMs(self) -> global___RangeConfig: ...
    @property
    def scStreamUpServerSecs(self) -> global___RangeConfig: ...
    @property
    def xmux(self) -> global___XmuxConfig: ...
    @property
    def downloadSettings(self) -> transport.internet.config_pb2.StreamConfig: ...
    def __init__(
        self,
        *,
        host: builtins.str = ...,
        path: builtins.str = ...,
        mode: builtins.str = ...,
        headers: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        xPaddingBytes: global___RangeConfig | None = ...,
        noGRPCHeader: builtins.bool = ...,
        noSSEHeader: builtins.bool = ...,
        scMaxEachPostBytes: global___RangeConfig | None = ...,
        scMinPostsIntervalMs: global___RangeConfig | None = ...,
        scMaxBufferedPosts: builtins.int = ...,
        scStreamUpServerSecs: global___RangeConfig | None = ...,
        xmux: global___XmuxConfig | None = ...,
        downloadSettings: transport.internet.config_pb2.StreamConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["downloadSettings", b"downloadSettings", "scMaxEachPostBytes", b"scMaxEachPostBytes", "scMinPostsIntervalMs", b"scMinPostsIntervalMs", "scStreamUpServerSecs", b"scStreamUpServerSecs", "xPaddingBytes", b"xPaddingBytes", "xmux", b"xmux"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["downloadSettings", b"downloadSettings", "headers", b"headers", "host", b"host", "mode", b"mode", "noGRPCHeader", b"noGRPCHeader", "noSSEHeader", b"noSSEHeader", "path", b"path", "scMaxBufferedPosts", b"scMaxBufferedPosts", "scMaxEachPostBytes", b"scMaxEachPostBytes", "scMinPostsIntervalMs", b"scMinPostsIntervalMs", "scStreamUpServerSecs", b"scStreamUpServerSecs", "xPaddingBytes", b"xPaddingBytes", "xmux", b"xmux"]) -> None: ...

global___Config = Config
