"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetStatsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    RESET_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of the stat counter."""
    reset: builtins.bool
    """Whether or not to reset the counter to fetching its value."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        reset: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "reset", b"reset"]) -> None: ...

global___GetStatsRequest = GetStatsRequest

@typing.final
class Stat(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: builtins.str
    value: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "value", b"value"]) -> None: ...

global___Stat = Stat

@typing.final
class GetStatsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STAT_FIELD_NUMBER: builtins.int
    @property
    def stat(self) -> global___Stat: ...
    def __init__(
        self,
        *,
        stat: global___Stat | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["stat", b"stat"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["stat", b"stat"]) -> None: ...

global___GetStatsResponse = GetStatsResponse

@typing.final
class QueryStatsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATTERN_FIELD_NUMBER: builtins.int
    RESET_FIELD_NUMBER: builtins.int
    pattern: builtins.str
    reset: builtins.bool
    def __init__(
        self,
        *,
        pattern: builtins.str = ...,
        reset: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pattern", b"pattern", "reset", b"reset"]) -> None: ...

global___QueryStatsRequest = QueryStatsRequest

@typing.final
class QueryStatsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STAT_FIELD_NUMBER: builtins.int
    @property
    def stat(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Stat]: ...
    def __init__(
        self,
        *,
        stat: collections.abc.Iterable[global___Stat] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["stat", b"stat"]) -> None: ...

global___QueryStatsResponse = QueryStatsResponse

@typing.final
class SysStatsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SysStatsRequest = SysStatsRequest

@typing.final
class SysStatsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NUMGOROUTINE_FIELD_NUMBER: builtins.int
    NUMGC_FIELD_NUMBER: builtins.int
    ALLOC_FIELD_NUMBER: builtins.int
    TOTALALLOC_FIELD_NUMBER: builtins.int
    SYS_FIELD_NUMBER: builtins.int
    MALLOCS_FIELD_NUMBER: builtins.int
    FREES_FIELD_NUMBER: builtins.int
    LIVEOBJECTS_FIELD_NUMBER: builtins.int
    PAUSETOTALNS_FIELD_NUMBER: builtins.int
    UPTIME_FIELD_NUMBER: builtins.int
    NumGoroutine: builtins.int
    NumGC: builtins.int
    Alloc: builtins.int
    TotalAlloc: builtins.int
    Sys: builtins.int
    Mallocs: builtins.int
    Frees: builtins.int
    LiveObjects: builtins.int
    PauseTotalNs: builtins.int
    Uptime: builtins.int
    def __init__(
        self,
        *,
        NumGoroutine: builtins.int = ...,
        NumGC: builtins.int = ...,
        Alloc: builtins.int = ...,
        TotalAlloc: builtins.int = ...,
        Sys: builtins.int = ...,
        Mallocs: builtins.int = ...,
        Frees: builtins.int = ...,
        LiveObjects: builtins.int = ...,
        PauseTotalNs: builtins.int = ...,
        Uptime: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Alloc", b"Alloc", "Frees", b"Frees", "LiveObjects", b"LiveObjects", "Mallocs", b"Mallocs", "NumGC", b"NumGC", "NumGoroutine", b"NumGoroutine", "PauseTotalNs", b"PauseTotalNs", "Sys", b"Sys", "TotalAlloc", b"TotalAlloc", "Uptime", b"Uptime"]) -> None: ...

global___SysStatsResponse = SysStatsResponse

@typing.final
class GetStatsOnlineIpListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class IpsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    IPS_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def ips(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.int]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        ips: collections.abc.Mapping[builtins.str, builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ips", b"ips", "name", b"name"]) -> None: ...

global___GetStatsOnlineIpListResponse = GetStatsOnlineIpListResponse

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Config = Config
