"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.protocol.server_spec_pb2
import common.protocol.user_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Account(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PASSWORD_FIELD_NUMBER: builtins.int
    password: builtins.str
    def __init__(
        self,
        *,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["password", b"password"]) -> None: ...

global___Account = Account

@typing.final
class Fallback(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ALPN_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DEST_FIELD_NUMBER: builtins.int
    XVER_FIELD_NUMBER: builtins.int
    name: builtins.str
    alpn: builtins.str
    path: builtins.str
    type: builtins.str
    dest: builtins.str
    xver: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        alpn: builtins.str = ...,
        path: builtins.str = ...,
        type: builtins.str = ...,
        dest: builtins.str = ...,
        xver: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["alpn", b"alpn", "dest", b"dest", "name", b"name", "path", b"path", "type", b"type", "xver", b"xver"]) -> None: ...

global___Fallback = Fallback

@typing.final
class ClientConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_FIELD_NUMBER: builtins.int
    @property
    def server(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.protocol.server_spec_pb2.ServerEndpoint]: ...
    def __init__(
        self,
        *,
        server: collections.abc.Iterable[common.protocol.server_spec_pb2.ServerEndpoint] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["server", b"server"]) -> None: ...

global___ClientConfig = ClientConfig

@typing.final
class ServerConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERS_FIELD_NUMBER: builtins.int
    FALLBACKS_FIELD_NUMBER: builtins.int
    @property
    def users(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.protocol.user_pb2.User]: ...
    @property
    def fallbacks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Fallback]: ...
    def __init__(
        self,
        *,
        users: collections.abc.Iterable[common.protocol.user_pb2.User] | None = ...,
        fallbacks: collections.abc.Iterable[global___Fallback] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["fallbacks", b"fallbacks", "users", b"users"]) -> None: ...

global___ServerConfig = ServerConfig
