"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import common.protocol.headers_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Account(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    SECURITY_SETTINGS_FIELD_NUMBER: builtins.int
    TESTS_ENABLED_FIELD_NUMBER: builtins.int
    id: builtins.str
    """ID of the account, in the form of a UUID, e.g.,
    "66ad4540-b58c-4ad2-9926-ea63445a9b57".
    """
    tests_enabled: builtins.str
    """Define tests enabled for this account"""
    @property
    def security_settings(self) -> common.protocol.headers_pb2.SecurityConfig:
        """Security settings. Only applies to client side."""

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        security_settings: common.protocol.headers_pb2.SecurityConfig | None = ...,
        tests_enabled: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["security_settings", b"security_settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "security_settings", b"security_settings", "tests_enabled", b"tests_enabled"]) -> None: ...

global___Account = Account
