"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Addons(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FLOW_FIELD_NUMBER: builtins.int
    SEED_FIELD_NUMBER: builtins.int
    Flow: builtins.str
    Seed: builtins.bytes
    def __init__(
        self,
        *,
        Flow: builtins.str = ...,
        Seed: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Flow", b"Flow", "Seed", b"Seed"]) -> None: ...

global___Addons = Addons
