"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Config = Config

@typing.final
class ChannelConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BLOCKING_FIELD_NUMBER: builtins.int
    SUBSCRIBERLIMIT_FIELD_NUMBER: builtins.int
    BUFFERSIZE_FIELD_NUMBER: builtins.int
    Blocking: builtins.bool
    SubscriberLimit: builtins.int
    BufferSize: builtins.int
    def __init__(
        self,
        *,
        Blocking: builtins.bool = ...,
        SubscriberLimit: builtins.int = ...,
        BufferSize: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Blocking", b"Blocking", "BufferSize", b"BufferSize", "SubscriberLimit", b"SubscriberLimit"]) -> None: ...

global___ChannelConfig = ChannelConfig
