"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import common.serial.typed_message_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_SETTINGS_FIELD_NUMBER: builtins.int
    ACCEPT_PROXY_PROTOCOL_FIELD_NUMBER: builtins.int
    accept_proxy_protocol: builtins.bool
    @property
    def header_settings(self) -> common.serial.typed_message_pb2.TypedMessage: ...
    def __init__(
        self,
        *,
        header_settings: common.serial.typed_message_pb2.TypedMessage | None = ...,
        accept_proxy_protocol: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["header_settings", b"header_settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["accept_proxy_protocol", b"accept_proxy_protocol", "header_settings", b"header_settings"]) -> None: ...

global___Config = Config
