"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import common.log.log_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _LogType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LogTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LogType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Console: _LogType.ValueType  # 1
    File: _LogType.ValueType  # 2
    Event: _LogType.ValueType  # 3

class LogType(_LogType, metaclass=_LogTypeEnumTypeWrapper): ...

Console: LogType.ValueType  # 1
File: LogType.ValueType  # 2
Event: LogType.ValueType  # 3
global___LogType = LogType

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_LOG_TYPE_FIELD_NUMBER: builtins.int
    ERROR_LOG_LEVEL_FIELD_NUMBER: builtins.int
    ERROR_LOG_PATH_FIELD_NUMBER: builtins.int
    ACCESS_LOG_TYPE_FIELD_NUMBER: builtins.int
    ACCESS_LOG_PATH_FIELD_NUMBER: builtins.int
    ENABLE_DNS_LOG_FIELD_NUMBER: builtins.int
    MASK_ADDRESS_FIELD_NUMBER: builtins.int
    error_log_type: global___LogType.ValueType
    error_log_level: common.log.log_pb2.Severity.ValueType
    error_log_path: builtins.str
    access_log_type: global___LogType.ValueType
    access_log_path: builtins.str
    enable_dns_log: builtins.bool
    mask_address: builtins.str
    def __init__(
        self,
        *,
        error_log_type: global___LogType.ValueType = ...,
        error_log_level: common.log.log_pb2.Severity.ValueType = ...,
        error_log_path: builtins.str = ...,
        access_log_type: global___LogType.ValueType = ...,
        access_log_path: builtins.str = ...,
        enable_dns_log: builtins.bool = ...,
        mask_address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_log_path", b"access_log_path", "access_log_type", b"access_log_type", "enable_dns_log", b"enable_dns_log", "error_log_level", b"error_log_level", "error_log_path", b"error_log_path", "error_log_type", b"error_log_type", "mask_address", b"mask_address"]) -> None: ...

global___Config = Config
