"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.protocol.server_spec_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Account(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["password", b"password", "username", b"username"]) -> None: ...

global___Account = Account

@typing.final
class ServerConfig(google.protobuf.message.Message):
    """Config for HTTP proxy server."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class AccountsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ACCOUNTS_FIELD_NUMBER: builtins.int
    ALLOW_TRANSPARENT_FIELD_NUMBER: builtins.int
    USER_LEVEL_FIELD_NUMBER: builtins.int
    allow_transparent: builtins.bool
    user_level: builtins.int
    @property
    def accounts(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        accounts: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        allow_transparent: builtins.bool = ...,
        user_level: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accounts", b"accounts", "allow_transparent", b"allow_transparent", "user_level", b"user_level"]) -> None: ...

global___ServerConfig = ServerConfig

@typing.final
class Header(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.str
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

global___Header = Header

@typing.final
class ClientConfig(google.protobuf.message.Message):
    """ClientConfig is the protobuf config for HTTP proxy client."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_FIELD_NUMBER: builtins.int
    HEADER_FIELD_NUMBER: builtins.int
    @property
    def server(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.protocol.server_spec_pb2.ServerEndpoint]:
        """Sever is a list of HTTP server addresses."""

    @property
    def header(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Header]: ...
    def __init__(
        self,
        *,
        server: collections.abc.Iterable[common.protocol.server_spec_pb2.ServerEndpoint] | None = ...,
        header: collections.abc.Iterable[global___Header] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "server", b"server"]) -> None: ...

global___ClientConfig = ClientConfig
