"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHOW_FIELD_NUMBER: builtins.int
    DEST_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    XVER_FIELD_NUMBER: builtins.int
    SERVER_NAMES_FIELD_NUMBER: builtins.int
    PRIVATE_KEY_FIELD_NUMBER: builtins.int
    MIN_CLIENT_VER_FIELD_NUMBER: builtins.int
    MAX_CLIENT_VER_FIELD_NUMBER: builtins.int
    MAX_TIME_DIFF_FIELD_NUMBER: builtins.int
    SHORT_IDS_FIELD_NUMBER: builtins.int
    MLDSA65_SEED_FIELD_NUMBER: builtins.int
    LIMIT_FALLBACK_UPLOAD_FIELD_NUMBER: builtins.int
    LIMIT_FALLBACK_DOWNLOAD_FIELD_NUMBER: builtins.int
    FINGERPRINT_FIELD_NUMBER: builtins.int
    SERVER_NAME_FIELD_NUMBER: builtins.int
    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    SHORT_ID_FIELD_NUMBER: builtins.int
    MLDSA65_VERIFY_FIELD_NUMBER: builtins.int
    SPIDER_X_FIELD_NUMBER: builtins.int
    SPIDER_Y_FIELD_NUMBER: builtins.int
    MASTER_KEY_LOG_FIELD_NUMBER: builtins.int
    show: builtins.bool
    dest: builtins.str
    type: builtins.str
    xver: builtins.int
    private_key: builtins.bytes
    min_client_ver: builtins.bytes
    max_client_ver: builtins.bytes
    max_time_diff: builtins.int
    mldsa65_seed: builtins.bytes
    Fingerprint: builtins.str
    server_name: builtins.str
    public_key: builtins.bytes
    short_id: builtins.bytes
    mldsa65_verify: builtins.bytes
    spider_x: builtins.str
    master_key_log: builtins.str
    @property
    def server_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def short_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def limit_fallback_upload(self) -> global___LimitFallback: ...
    @property
    def limit_fallback_download(self) -> global___LimitFallback: ...
    @property
    def spider_y(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        show: builtins.bool = ...,
        dest: builtins.str = ...,
        type: builtins.str = ...,
        xver: builtins.int = ...,
        server_names: collections.abc.Iterable[builtins.str] | None = ...,
        private_key: builtins.bytes = ...,
        min_client_ver: builtins.bytes = ...,
        max_client_ver: builtins.bytes = ...,
        max_time_diff: builtins.int = ...,
        short_ids: collections.abc.Iterable[builtins.bytes] | None = ...,
        mldsa65_seed: builtins.bytes = ...,
        limit_fallback_upload: global___LimitFallback | None = ...,
        limit_fallback_download: global___LimitFallback | None = ...,
        Fingerprint: builtins.str = ...,
        server_name: builtins.str = ...,
        public_key: builtins.bytes = ...,
        short_id: builtins.bytes = ...,
        mldsa65_verify: builtins.bytes = ...,
        spider_x: builtins.str = ...,
        spider_y: collections.abc.Iterable[builtins.int] | None = ...,
        master_key_log: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["limit_fallback_download", b"limit_fallback_download", "limit_fallback_upload", b"limit_fallback_upload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Fingerprint", b"Fingerprint", "dest", b"dest", "limit_fallback_download", b"limit_fallback_download", "limit_fallback_upload", b"limit_fallback_upload", "master_key_log", b"master_key_log", "max_client_ver", b"max_client_ver", "max_time_diff", b"max_time_diff", "min_client_ver", b"min_client_ver", "mldsa65_seed", b"mldsa65_seed", "mldsa65_verify", b"mldsa65_verify", "private_key", b"private_key", "public_key", b"public_key", "server_name", b"server_name", "server_names", b"server_names", "short_id", b"short_id", "short_ids", b"short_ids", "show", b"show", "spider_x", b"spider_x", "spider_y", b"spider_y", "type", b"type", "xver", b"xver"]) -> None: ...

global___Config = Config

@typing.final
class LimitFallback(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AFTER_BYTES_FIELD_NUMBER: builtins.int
    BYTES_PER_SEC_FIELD_NUMBER: builtins.int
    BURST_BYTES_PER_SEC_FIELD_NUMBER: builtins.int
    after_bytes: builtins.int
    bytes_per_sec: builtins.int
    burst_bytes_per_sec: builtins.int
    def __init__(
        self,
        *,
        after_bytes: builtins.int = ...,
        bytes_per_sec: builtins.int = ...,
        burst_bytes_per_sec: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["after_bytes", b"after_bytes", "burst_bytes_per_sec", b"burst_bytes_per_sec", "bytes_per_sec", b"bytes_per_sec"]) -> None: ...

global___LimitFallback = LimitFallback
