"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class FakeDnsPool(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IP_POOL_FIELD_NUMBER: builtins.int
    LRUSIZE_FIELD_NUMBER: builtins.int
    ip_pool: builtins.str
    """CIDR of IP pool used as fake DNS IP"""
    lruSize: builtins.int
    """Size of Pool for remembering relationship between domain name and IP address"""
    def __init__(
        self,
        *,
        ip_pool: builtins.str = ...,
        lruSize: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ip_pool", b"ip_pool", "lruSize", b"lruSize"]) -> None: ...

global___FakeDnsPool = FakeDnsPool

@typing.final
class FakeDnsPoolMulti(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POOLS_FIELD_NUMBER: builtins.int
    @property
    def pools(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FakeDnsPool]: ...
    def __init__(
        self,
        *,
        pools: collections.abc.Iterable[global___FakeDnsPool] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pools", b"pools"]) -> None: ...

global___FakeDnsPoolMulti = FakeDnsPoolMulti
