"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PeerConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    PRE_SHARED_KEY_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    KEEP_ALIVE_FIELD_NUMBER: builtins.int
    ALLOWED_IPS_FIELD_NUMBER: builtins.int
    public_key: builtins.str
    pre_shared_key: builtins.str
    endpoint: builtins.str
    keep_alive: builtins.int
    @property
    def allowed_ips(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        public_key: builtins.str = ...,
        pre_shared_key: builtins.str = ...,
        endpoint: builtins.str = ...,
        keep_alive: builtins.int = ...,
        allowed_ips: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["allowed_ips", b"allowed_ips", "endpoint", b"endpoint", "keep_alive", b"keep_alive", "pre_shared_key", b"pre_shared_key", "public_key", b"public_key"]) -> None: ...

global___PeerConfig = PeerConfig

@typing.final
class DeviceConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _DomainStrategy:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DomainStrategyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DeviceConfig._DomainStrategy.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        FORCE_IP: DeviceConfig._DomainStrategy.ValueType  # 0
        FORCE_IP4: DeviceConfig._DomainStrategy.ValueType  # 1
        FORCE_IP6: DeviceConfig._DomainStrategy.ValueType  # 2
        FORCE_IP46: DeviceConfig._DomainStrategy.ValueType  # 3
        FORCE_IP64: DeviceConfig._DomainStrategy.ValueType  # 4

    class DomainStrategy(_DomainStrategy, metaclass=_DomainStrategyEnumTypeWrapper): ...
    FORCE_IP: DeviceConfig.DomainStrategy.ValueType  # 0
    FORCE_IP4: DeviceConfig.DomainStrategy.ValueType  # 1
    FORCE_IP6: DeviceConfig.DomainStrategy.ValueType  # 2
    FORCE_IP46: DeviceConfig.DomainStrategy.ValueType  # 3
    FORCE_IP64: DeviceConfig.DomainStrategy.ValueType  # 4

    SECRET_KEY_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    PEERS_FIELD_NUMBER: builtins.int
    MTU_FIELD_NUMBER: builtins.int
    NUM_WORKERS_FIELD_NUMBER: builtins.int
    RESERVED_FIELD_NUMBER: builtins.int
    DOMAIN_STRATEGY_FIELD_NUMBER: builtins.int
    IS_CLIENT_FIELD_NUMBER: builtins.int
    NO_KERNEL_TUN_FIELD_NUMBER: builtins.int
    secret_key: builtins.str
    mtu: builtins.int
    num_workers: builtins.int
    reserved: builtins.bytes
    domain_strategy: global___DeviceConfig.DomainStrategy.ValueType
    is_client: builtins.bool
    no_kernel_tun: builtins.bool
    @property
    def endpoint(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def peers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PeerConfig]: ...
    def __init__(
        self,
        *,
        secret_key: builtins.str = ...,
        endpoint: collections.abc.Iterable[builtins.str] | None = ...,
        peers: collections.abc.Iterable[global___PeerConfig] | None = ...,
        mtu: builtins.int = ...,
        num_workers: builtins.int = ...,
        reserved: builtins.bytes = ...,
        domain_strategy: global___DeviceConfig.DomainStrategy.ValueType = ...,
        is_client: builtins.bool = ...,
        no_kernel_tun: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["domain_strategy", b"domain_strategy", "endpoint", b"endpoint", "is_client", b"is_client", "mtu", b"mtu", "no_kernel_tun", b"no_kernel_tun", "num_workers", b"num_workers", "peers", b"peers", "reserved", b"reserved", "secret_key", b"secret_key"]) -> None: ...

global___DeviceConfig = DeviceConfig
