"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Second(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.int
    def __init__(
        self,
        *,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___Second = Second

@typing.final
class Policy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Timeout(google.protobuf.message.Message):
        """Timeout is a message for timeout settings in various stages, in seconds."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        HANDSHAKE_FIELD_NUMBER: builtins.int
        CONNECTION_IDLE_FIELD_NUMBER: builtins.int
        UPLINK_ONLY_FIELD_NUMBER: builtins.int
        DOWNLINK_ONLY_FIELD_NUMBER: builtins.int
        @property
        def handshake(self) -> global___Second: ...
        @property
        def connection_idle(self) -> global___Second: ...
        @property
        def uplink_only(self) -> global___Second: ...
        @property
        def downlink_only(self) -> global___Second: ...
        def __init__(
            self,
            *,
            handshake: global___Second | None = ...,
            connection_idle: global___Second | None = ...,
            uplink_only: global___Second | None = ...,
            downlink_only: global___Second | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["connection_idle", b"connection_idle", "downlink_only", b"downlink_only", "handshake", b"handshake", "uplink_only", b"uplink_only"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["connection_idle", b"connection_idle", "downlink_only", b"downlink_only", "handshake", b"handshake", "uplink_only", b"uplink_only"]) -> None: ...

    @typing.final
    class Stats(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        USER_UPLINK_FIELD_NUMBER: builtins.int
        USER_DOWNLINK_FIELD_NUMBER: builtins.int
        USER_ONLINE_FIELD_NUMBER: builtins.int
        user_uplink: builtins.bool
        user_downlink: builtins.bool
        user_online: builtins.bool
        def __init__(
            self,
            *,
            user_uplink: builtins.bool = ...,
            user_downlink: builtins.bool = ...,
            user_online: builtins.bool = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["user_downlink", b"user_downlink", "user_online", b"user_online", "user_uplink", b"user_uplink"]) -> None: ...

    @typing.final
    class Buffer(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CONNECTION_FIELD_NUMBER: builtins.int
        connection: builtins.int
        """Buffer size per connection, in bytes. -1 for unlimited buffer."""
        def __init__(
            self,
            *,
            connection: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["connection", b"connection"]) -> None: ...

    TIMEOUT_FIELD_NUMBER: builtins.int
    STATS_FIELD_NUMBER: builtins.int
    BUFFER_FIELD_NUMBER: builtins.int
    @property
    def timeout(self) -> global___Policy.Timeout: ...
    @property
    def stats(self) -> global___Policy.Stats: ...
    @property
    def buffer(self) -> global___Policy.Buffer: ...
    def __init__(
        self,
        *,
        timeout: global___Policy.Timeout | None = ...,
        stats: global___Policy.Stats | None = ...,
        buffer: global___Policy.Buffer | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["buffer", b"buffer", "stats", b"stats", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["buffer", b"buffer", "stats", b"stats", "timeout", b"timeout"]) -> None: ...

global___Policy = Policy

@typing.final
class SystemPolicy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Stats(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INBOUND_UPLINK_FIELD_NUMBER: builtins.int
        INBOUND_DOWNLINK_FIELD_NUMBER: builtins.int
        OUTBOUND_UPLINK_FIELD_NUMBER: builtins.int
        OUTBOUND_DOWNLINK_FIELD_NUMBER: builtins.int
        inbound_uplink: builtins.bool
        inbound_downlink: builtins.bool
        outbound_uplink: builtins.bool
        outbound_downlink: builtins.bool
        def __init__(
            self,
            *,
            inbound_uplink: builtins.bool = ...,
            inbound_downlink: builtins.bool = ...,
            outbound_uplink: builtins.bool = ...,
            outbound_downlink: builtins.bool = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["inbound_downlink", b"inbound_downlink", "inbound_uplink", b"inbound_uplink", "outbound_downlink", b"outbound_downlink", "outbound_uplink", b"outbound_uplink"]) -> None: ...

    STATS_FIELD_NUMBER: builtins.int
    @property
    def stats(self) -> global___SystemPolicy.Stats: ...
    def __init__(
        self,
        *,
        stats: global___SystemPolicy.Stats | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["stats", b"stats"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["stats", b"stats"]) -> None: ...

global___SystemPolicy = SystemPolicy

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class LevelEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___Policy: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___Policy | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    LEVEL_FIELD_NUMBER: builtins.int
    SYSTEM_FIELD_NUMBER: builtins.int
    @property
    def level(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___Policy]: ...
    @property
    def system(self) -> global___SystemPolicy: ...
    def __init__(
        self,
        *,
        level: collections.abc.Mapping[builtins.int, global___Policy] | None = ...,
        system: global___SystemPolicy | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["system", b"system"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["level", b"level", "system", b"system"]) -> None: ...

global___Config = Config
