"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    PADDING_FIELD_NUMBER: builtins.int
    EXTENSION_FIELD_NUMBER: builtins.int
    CSRC_COUNT_FIELD_NUMBER: builtins.int
    MARKER_FIELD_NUMBER: builtins.int
    PAYLOAD_TYPE_FIELD_NUMBER: builtins.int
    version: builtins.int
    padding: builtins.bool
    extension: builtins.bool
    csrc_count: builtins.int
    marker: builtins.bool
    payload_type: builtins.int
    def __init__(
        self,
        *,
        version: builtins.int = ...,
        padding: builtins.bool = ...,
        extension: builtins.bool = ...,
        csrc_count: builtins.int = ...,
        marker: builtins.bool = ...,
        payload_type: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["csrc_count", b"csrc_count", "extension", b"extension", "marker", b"marker", "padding", b"padding", "payload_type", b"payload_type", "version", b"version"]) -> None: ...

global___Config = Config
