"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.net.network_pb2
import common.serial.typed_message_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RoutingContext(google.protobuf.message.Message):
    """RoutingContext is the context with information relative to routing process.
    It conforms to the structure of xray.features.routing.Context and
    xray.features.routing.Route.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class AttributesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    INBOUNDTAG_FIELD_NUMBER: builtins.int
    NETWORK_FIELD_NUMBER: builtins.int
    SOURCEIPS_FIELD_NUMBER: builtins.int
    TARGETIPS_FIELD_NUMBER: builtins.int
    SOURCEPORT_FIELD_NUMBER: builtins.int
    TARGETPORT_FIELD_NUMBER: builtins.int
    TARGETDOMAIN_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    OUTBOUNDGROUPTAGS_FIELD_NUMBER: builtins.int
    OUTBOUNDTAG_FIELD_NUMBER: builtins.int
    LOCALIPS_FIELD_NUMBER: builtins.int
    LOCALPORT_FIELD_NUMBER: builtins.int
    VLESSROUTE_FIELD_NUMBER: builtins.int
    InboundTag: builtins.str
    Network: common.net.network_pb2.Network.ValueType
    SourcePort: builtins.int
    TargetPort: builtins.int
    TargetDomain: builtins.str
    Protocol: builtins.str
    User: builtins.str
    OutboundTag: builtins.str
    LocalPort: builtins.int
    VlessRoute: builtins.int
    @property
    def SourceIPs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def TargetIPs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def Attributes(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def OutboundGroupTags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def LocalIPs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        InboundTag: builtins.str = ...,
        Network: common.net.network_pb2.Network.ValueType = ...,
        SourceIPs: collections.abc.Iterable[builtins.bytes] | None = ...,
        TargetIPs: collections.abc.Iterable[builtins.bytes] | None = ...,
        SourcePort: builtins.int = ...,
        TargetPort: builtins.int = ...,
        TargetDomain: builtins.str = ...,
        Protocol: builtins.str = ...,
        User: builtins.str = ...,
        Attributes: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        OutboundGroupTags: collections.abc.Iterable[builtins.str] | None = ...,
        OutboundTag: builtins.str = ...,
        LocalIPs: collections.abc.Iterable[builtins.bytes] | None = ...,
        LocalPort: builtins.int = ...,
        VlessRoute: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Attributes", b"Attributes", "InboundTag", b"InboundTag", "LocalIPs", b"LocalIPs", "LocalPort", b"LocalPort", "Network", b"Network", "OutboundGroupTags", b"OutboundGroupTags", "OutboundTag", b"OutboundTag", "Protocol", b"Protocol", "SourceIPs", b"SourceIPs", "SourcePort", b"SourcePort", "TargetDomain", b"TargetDomain", "TargetIPs", b"TargetIPs", "TargetPort", b"TargetPort", "User", b"User", "VlessRoute", b"VlessRoute"]) -> None: ...

global___RoutingContext = RoutingContext

@typing.final
class SubscribeRoutingStatsRequest(google.protobuf.message.Message):
    """SubscribeRoutingStatsRequest subscribes to routing statistics channel if
    opened by xray-core.
    * FieldSelectors selects a subset of fields in routing statistics to return.
    Valid selectors:
     - inbound: Selects connection's inbound tag.
     - network: Selects connection's network.
     - ip: Equivalent as "ip_source" and "ip_target", selects both source and
     target IP.
     - port: Equivalent as "port_source" and "port_target", selects both source
     and target port.
     - domain: Selects target domain.
     - protocol: Select connection's protocol.
     - user: Select connection's inbound user email.
     - attributes: Select connection's additional attributes.
     - outbound: Equivalent as "outbound" and "outbound_group", select both
     outbound tag and outbound group tags.
    * If FieldSelectors is left empty, all fields will be returned.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIELDSELECTORS_FIELD_NUMBER: builtins.int
    @property
    def FieldSelectors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        FieldSelectors: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["FieldSelectors", b"FieldSelectors"]) -> None: ...

global___SubscribeRoutingStatsRequest = SubscribeRoutingStatsRequest

@typing.final
class TestRouteRequest(google.protobuf.message.Message):
    """TestRouteRequest manually tests a routing result according to the routing
    context message.
    * RoutingContext is the routing message without outbound information.
    * FieldSelectors selects the fields to return in the routing result. All
    fields are returned if left empty.
    * PublishResult broadcasts the routing result to routing statistics channel
    if set true.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROUTINGCONTEXT_FIELD_NUMBER: builtins.int
    FIELDSELECTORS_FIELD_NUMBER: builtins.int
    PUBLISHRESULT_FIELD_NUMBER: builtins.int
    PublishResult: builtins.bool
    @property
    def RoutingContext(self) -> global___RoutingContext: ...
    @property
    def FieldSelectors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        RoutingContext: global___RoutingContext | None = ...,
        FieldSelectors: collections.abc.Iterable[builtins.str] | None = ...,
        PublishResult: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["RoutingContext", b"RoutingContext"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["FieldSelectors", b"FieldSelectors", "PublishResult", b"PublishResult", "RoutingContext", b"RoutingContext"]) -> None: ...

global___TestRouteRequest = TestRouteRequest

@typing.final
class PrincipleTargetInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    @property
    def tag(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        tag: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["tag", b"tag"]) -> None: ...

global___PrincipleTargetInfo = PrincipleTargetInfo

@typing.final
class OverrideInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TARGET_FIELD_NUMBER: builtins.int
    target: builtins.str
    def __init__(
        self,
        *,
        target: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["target", b"target"]) -> None: ...

global___OverrideInfo = OverrideInfo

@typing.final
class BalancerMsg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OVERRIDE_FIELD_NUMBER: builtins.int
    PRINCIPLE_TARGET_FIELD_NUMBER: builtins.int
    @property
    def override(self) -> global___OverrideInfo: ...
    @property
    def principle_target(self) -> global___PrincipleTargetInfo: ...
    def __init__(
        self,
        *,
        override: global___OverrideInfo | None = ...,
        principle_target: global___PrincipleTargetInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["override", b"override", "principle_target", b"principle_target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["override", b"override", "principle_target", b"principle_target"]) -> None: ...

global___BalancerMsg = BalancerMsg

@typing.final
class GetBalancerInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    tag: builtins.str
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["tag", b"tag"]) -> None: ...

global___GetBalancerInfoRequest = GetBalancerInfoRequest

@typing.final
class GetBalancerInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BALANCER_FIELD_NUMBER: builtins.int
    @property
    def balancer(self) -> global___BalancerMsg: ...
    def __init__(
        self,
        *,
        balancer: global___BalancerMsg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["balancer", b"balancer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["balancer", b"balancer"]) -> None: ...

global___GetBalancerInfoResponse = GetBalancerInfoResponse

@typing.final
class OverrideBalancerTargetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BALANCERTAG_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    balancerTag: builtins.str
    target: builtins.str
    def __init__(
        self,
        *,
        balancerTag: builtins.str = ...,
        target: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["balancerTag", b"balancerTag", "target", b"target"]) -> None: ...

global___OverrideBalancerTargetRequest = OverrideBalancerTargetRequest

@typing.final
class OverrideBalancerTargetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___OverrideBalancerTargetResponse = OverrideBalancerTargetResponse

@typing.final
class AddRuleRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_FIELD_NUMBER: builtins.int
    SHOULDAPPEND_FIELD_NUMBER: builtins.int
    shouldAppend: builtins.bool
    @property
    def config(self) -> common.serial.typed_message_pb2.TypedMessage: ...
    def __init__(
        self,
        *,
        config: common.serial.typed_message_pb2.TypedMessage | None = ...,
        shouldAppend: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "shouldAppend", b"shouldAppend"]) -> None: ...

global___AddRuleRequest = AddRuleRequest

@typing.final
class AddRuleResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AddRuleResponse = AddRuleResponse

@typing.final
class RemoveRuleRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RULETAG_FIELD_NUMBER: builtins.int
    ruleTag: builtins.str
    def __init__(
        self,
        *,
        ruleTag: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ruleTag", b"ruleTag"]) -> None: ...

global___RemoveRuleRequest = RemoveRuleRequest

@typing.final
class RemoveRuleResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RemoveRuleResponse = RemoveRuleResponse

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Config = Config
