"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.serial.typed_message_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    """Config is the settings for Commander."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    LISTEN_FIELD_NUMBER: builtins.int
    SERVICE_FIELD_NUMBER: builtins.int
    tag: builtins.str
    """Tag of the outbound handler that handles grpc connections."""
    listen: builtins.str
    """Network address of commander grpc service."""
    @property
    def service(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.serial.typed_message_pb2.TypedMessage]:
        """Services that supported by this server. All services must implement Service
        interface.
        """

    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        listen: builtins.str = ...,
        service: collections.abc.Iterable[common.serial.typed_message_pb2.TypedMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["listen", b"listen", "service", b"service", "tag", b"tag"]) -> None: ...

global___Config = Config

@typing.final
class ReflectionConfig(google.protobuf.message.Message):
    """ReflectionConfig is the placeholder config for ReflectionService."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ReflectionConfig = ReflectionConfig
