"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.net.destination_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_FIELD_NUMBER: builtins.int
    USER_LEVEL_FIELD_NUMBER: builtins.int
    NON_IP_QUERY_FIELD_NUMBER: builtins.int
    BLOCK_TYPES_FIELD_NUMBER: builtins.int
    user_level: builtins.int
    non_IP_query: builtins.str
    @property
    def server(self) -> common.net.destination_pb2.Endpoint:
        """Server is the DNS server address. If specified, this address overrides the
        original one.
        """

    @property
    def block_types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        server: common.net.destination_pb2.Endpoint | None = ...,
        user_level: builtins.int = ...,
        non_IP_query: builtins.str = ...,
        block_types: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["server", b"server"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["block_types", b"block_types", "non_IP_query", b"non_IP_query", "server", b"server", "user_level", b"user_level"]) -> None: ...

global___Config = Config
