"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Header(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: builtins.str
    """"Accept", "Cookie", etc"""
    @property
    def value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Each entry must be valid in one piece. Random entry will be chosen if
        multiple entries present.
        """

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        value: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "value", b"value"]) -> None: ...

global___Header = Header

@typing.final
class Version(google.protobuf.message.Message):
    """HTTP version. Default value "1.1"."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.str
    def __init__(
        self,
        *,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___Version = Version

@typing.final
class Method(google.protobuf.message.Message):
    """HTTP method. Default value "GET"."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.str
    def __init__(
        self,
        *,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___Method = Method

@typing.final
class RequestConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    HEADER_FIELD_NUMBER: builtins.int
    @property
    def version(self) -> global___Version:
        """Full HTTP version like "1.1"."""

    @property
    def method(self) -> global___Method:
        """GET, POST, CONNECT etc"""

    @property
    def uri(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """URI like "/login.php" """

    @property
    def header(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Header]: ...
    def __init__(
        self,
        *,
        version: global___Version | None = ...,
        method: global___Method | None = ...,
        uri: collections.abc.Iterable[builtins.str] | None = ...,
        header: collections.abc.Iterable[global___Header] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["method", b"method", "version", b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "method", b"method", "uri", b"uri", "version", b"version"]) -> None: ...

global___RequestConfig = RequestConfig

@typing.final
class Status(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    code: builtins.str
    """Status code. Default "200"."""
    reason: builtins.str
    """Statue reason. Default "OK"."""
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        reason: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "reason", b"reason"]) -> None: ...

global___Status = Status

@typing.final
class ResponseConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    HEADER_FIELD_NUMBER: builtins.int
    @property
    def version(self) -> global___Version: ...
    @property
    def status(self) -> global___Status: ...
    @property
    def header(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Header]: ...
    def __init__(
        self,
        *,
        version: global___Version | None = ...,
        status: global___Status | None = ...,
        header: collections.abc.Iterable[global___Header] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["status", b"status", "version", b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "status", b"status", "version", b"version"]) -> None: ...

global___ResponseConfig = ResponseConfig

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def request(self) -> global___RequestConfig:
        """Settings for authenticating requests. If not set, client side will not send
        authentication header, and server side will bypass authentication.
        """

    @property
    def response(self) -> global___ResponseConfig:
        """Settings for authenticating responses. If not set, client side will bypass
        authentication, and server side will not send authentication header.
        """

    def __init__(
        self,
        *,
        request: global___RequestConfig | None = ...,
        response: global___ResponseConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["request", b"request", "response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["request", b"request", "response", b"response"]) -> None: ...

global___Config = Config
