"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SecurityType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SecurityTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SecurityType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _SecurityType.ValueType  # 0
    AUTO: _SecurityType.ValueType  # 2
    AES128_GCM: _SecurityType.ValueType  # 3
    CHACHA20_POLY1305: _SecurityType.ValueType  # 4
    NONE: _SecurityType.ValueType  # 5
    """[DEPRECATED 2023-06]"""
    ZERO: _SecurityType.ValueType  # 6

class SecurityType(_SecurityType, metaclass=_SecurityTypeEnumTypeWrapper): ...

UNKNOWN: SecurityType.ValueType  # 0
AUTO: SecurityType.ValueType  # 2
AES128_GCM: SecurityType.ValueType  # 3
CHACHA20_POLY1305: SecurityType.ValueType  # 4
NONE: SecurityType.ValueType  # 5
"""[DEPRECATED 2023-06]"""
ZERO: SecurityType.ValueType  # 6
global___SecurityType = SecurityType

@typing.final
class SecurityConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    type: global___SecurityType.ValueType
    def __init__(
        self,
        *,
        type: global___SecurityType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["type", b"type"]) -> None: ...

global___SecurityConfig = SecurityConfig
