"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.net.address_pb2
import common.protocol.user_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ServerEndpoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    port: builtins.int
    @property
    def address(self) -> common.net.address_pb2.IPOrDomain: ...
    @property
    def user(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.protocol.user_pb2.User]: ...
    def __init__(
        self,
        *,
        address: common.net.address_pb2.IPOrDomain | None = ...,
        port: builtins.int = ...,
        user: collections.abc.Iterable[common.protocol.user_pb2.User] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "port", b"port", "user", b"user"]) -> None: ...

global___ServerEndpoint = ServerEndpoint
