"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import common.serial.typed_message_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class User(google.protobuf.message.Message):
    """User is a generic user for all protocols."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEVEL_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    ACCOUNT_FIELD_NUMBER: builtins.int
    level: builtins.int
    email: builtins.str
    @property
    def account(self) -> common.serial.typed_message_pb2.TypedMessage:
        """Protocol specific account information. Must be the account proto in one of
        the proxies.
        """

    def __init__(
        self,
        *,
        level: builtins.int = ...,
        email: builtins.str = ...,
        account: common.serial.typed_message_pb2.TypedMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account", b"account"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account", b"account", "email", b"email", "level", b"level"]) -> None: ...

global___User = User
