"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Control(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _State:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Control._State.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ACTIVE: Control._State.ValueType  # 0
        DRAIN: Control._State.ValueType  # 1

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    ACTIVE: Control.State.ValueType  # 0
    DRAIN: Control.State.ValueType  # 1

    STATE_FIELD_NUMBER: builtins.int
    RANDOM_FIELD_NUMBER: builtins.int
    state: global___Control.State.ValueType
    random: builtins.bytes
    def __init__(
        self,
        *,
        state: global___Control.State.ValueType = ...,
        random: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["random", b"random", "state", b"state"]) -> None: ...

global___Control = Control

@typing.final
class BridgeConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    tag: builtins.str
    domain: builtins.str
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        domain: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["domain", b"domain", "tag", b"tag"]) -> None: ...

global___BridgeConfig = BridgeConfig

@typing.final
class PortalConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    tag: builtins.str
    domain: builtins.str
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        domain: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["domain", b"domain", "tag", b"tag"]) -> None: ...

global___PortalConfig = PortalConfig

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BRIDGE_CONFIG_FIELD_NUMBER: builtins.int
    PORTAL_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def bridge_config(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BridgeConfig]: ...
    @property
    def portal_config(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PortalConfig]: ...
    def __init__(
        self,
        *,
        bridge_config: collections.abc.Iterable[global___BridgeConfig] | None = ...,
        portal_config: collections.abc.Iterable[global___PortalConfig] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bridge_config", b"bridge_config", "portal_config", b"portal_config"]) -> None: ...

global___Config = Config
