"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.net.address_pb2
import common.net.network_pb2
import common.protocol.user_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ServerConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METHOD_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    NETWORK_FIELD_NUMBER: builtins.int
    method: builtins.str
    key: builtins.str
    email: builtins.str
    level: builtins.int
    @property
    def network(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[common.net.network_pb2.Network.ValueType]: ...
    def __init__(
        self,
        *,
        method: builtins.str = ...,
        key: builtins.str = ...,
        email: builtins.str = ...,
        level: builtins.int = ...,
        network: collections.abc.Iterable[common.net.network_pb2.Network.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "key", b"key", "level", b"level", "method", b"method", "network", b"network"]) -> None: ...

global___ServerConfig = ServerConfig

@typing.final
class MultiUserServerConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METHOD_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    USERS_FIELD_NUMBER: builtins.int
    NETWORK_FIELD_NUMBER: builtins.int
    method: builtins.str
    key: builtins.str
    @property
    def users(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.protocol.user_pb2.User]: ...
    @property
    def network(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[common.net.network_pb2.Network.ValueType]: ...
    def __init__(
        self,
        *,
        method: builtins.str = ...,
        key: builtins.str = ...,
        users: collections.abc.Iterable[common.protocol.user_pb2.User] | None = ...,
        network: collections.abc.Iterable[common.net.network_pb2.Network.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "method", b"method", "network", b"network", "users", b"users"]) -> None: ...

global___MultiUserServerConfig = MultiUserServerConfig

@typing.final
class RelayDestination(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    key: builtins.str
    port: builtins.int
    email: builtins.str
    level: builtins.int
    @property
    def address(self) -> common.net.address_pb2.IPOrDomain: ...
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        address: common.net.address_pb2.IPOrDomain | None = ...,
        port: builtins.int = ...,
        email: builtins.str = ...,
        level: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "email", b"email", "key", b"key", "level", b"level", "port", b"port"]) -> None: ...

global___RelayDestination = RelayDestination

@typing.final
class RelayServerConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METHOD_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    DESTINATIONS_FIELD_NUMBER: builtins.int
    NETWORK_FIELD_NUMBER: builtins.int
    method: builtins.str
    key: builtins.str
    @property
    def destinations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RelayDestination]: ...
    @property
    def network(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[common.net.network_pb2.Network.ValueType]: ...
    def __init__(
        self,
        *,
        method: builtins.str = ...,
        key: builtins.str = ...,
        destinations: collections.abc.Iterable[global___RelayDestination] | None = ...,
        network: collections.abc.Iterable[common.net.network_pb2.Network.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["destinations", b"destinations", "key", b"key", "method", b"method", "network", b"network"]) -> None: ...

global___RelayServerConfig = RelayServerConfig

@typing.final
class Account(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    key: builtins.str
    def __init__(
        self,
        *,
        key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["key", b"key"]) -> None: ...

global___Account = Account

@typing.final
class ClientConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    UDP_OVER_TCP_FIELD_NUMBER: builtins.int
    UDP_OVER_TCP_VERSION_FIELD_NUMBER: builtins.int
    port: builtins.int
    method: builtins.str
    key: builtins.str
    udp_over_tcp: builtins.bool
    udp_over_tcp_version: builtins.int
    @property
    def address(self) -> common.net.address_pb2.IPOrDomain: ...
    def __init__(
        self,
        *,
        address: common.net.address_pb2.IPOrDomain | None = ...,
        port: builtins.int = ...,
        method: builtins.str = ...,
        key: builtins.str = ...,
        udp_over_tcp: builtins.bool = ...,
        udp_over_tcp_version: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "key", b"key", "method", b"method", "port", b"port", "udp_over_tcp", b"udp_over_tcp", "udp_over_tcp_version", b"udp_over_tcp_version"]) -> None: ...

global___ClientConfig = ClientConfig
