"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Account(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    FLOW_FIELD_NUMBER: builtins.int
    ENCRYPTION_FIELD_NUMBER: builtins.int
    XORMODE_FIELD_NUMBER: builtins.int
    SECONDS_FIELD_NUMBER: builtins.int
    PADDING_FIELD_NUMBER: builtins.int
    id: builtins.str
    """ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57"."""
    flow: builtins.str
    """Flow settings. May be "xtls-rprx-vision"."""
    encryption: builtins.str
    xorMode: builtins.int
    seconds: builtins.int
    padding: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        flow: builtins.str = ...,
        encryption: builtins.str = ...,
        xorMode: builtins.int = ...,
        seconds: builtins.int = ...,
        padding: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["encryption", b"encryption", "flow", b"flow", "id", b"id", "padding", b"padding", "seconds", b"seconds", "xorMode", b"xorMode"]) -> None: ...

global___Account = Account
