"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.protocol.user_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Fallback(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ALPN_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DEST_FIELD_NUMBER: builtins.int
    XVER_FIELD_NUMBER: builtins.int
    name: builtins.str
    alpn: builtins.str
    path: builtins.str
    type: builtins.str
    dest: builtins.str
    xver: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        alpn: builtins.str = ...,
        path: builtins.str = ...,
        type: builtins.str = ...,
        dest: builtins.str = ...,
        xver: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["alpn", b"alpn", "dest", b"dest", "name", b"name", "path", b"path", "type", b"type", "xver", b"xver"]) -> None: ...

global___Fallback = Fallback

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENTS_FIELD_NUMBER: builtins.int
    FALLBACKS_FIELD_NUMBER: builtins.int
    DECRYPTION_FIELD_NUMBER: builtins.int
    XORMODE_FIELD_NUMBER: builtins.int
    SECONDS_FROM_FIELD_NUMBER: builtins.int
    SECONDS_TO_FIELD_NUMBER: builtins.int
    PADDING_FIELD_NUMBER: builtins.int
    decryption: builtins.str
    xorMode: builtins.int
    seconds_from: builtins.int
    seconds_to: builtins.int
    padding: builtins.str
    @property
    def clients(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.protocol.user_pb2.User]: ...
    @property
    def fallbacks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Fallback]: ...
    def __init__(
        self,
        *,
        clients: collections.abc.Iterable[common.protocol.user_pb2.User] | None = ...,
        fallbacks: collections.abc.Iterable[global___Fallback] | None = ...,
        decryption: builtins.str = ...,
        xorMode: builtins.int = ...,
        seconds_from: builtins.int = ...,
        seconds_to: builtins.int = ...,
        padding: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["clients", b"clients", "decryption", b"decryption", "fallbacks", b"fallbacks", "padding", b"padding", "seconds_from", b"seconds_from", "seconds_to", b"seconds_to", "xorMode", b"xorMode"]) -> None: ...

global___Config = Config
