"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import common.serial.typed_message_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MTU(google.protobuf.message.Message):
    """Maximum Transmission Unit, in bytes."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.int
    def __init__(
        self,
        *,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___MTU = MTU

@typing.final
class TTI(google.protobuf.message.Message):
    """Transmission Time Interview, in milli-sec."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.int
    def __init__(
        self,
        *,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___TTI = TTI

@typing.final
class UplinkCapacity(google.protobuf.message.Message):
    """Uplink capacity, in MB."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.int
    def __init__(
        self,
        *,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___UplinkCapacity = UplinkCapacity

@typing.final
class DownlinkCapacity(google.protobuf.message.Message):
    """Downlink capacity, in MB."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.int
    def __init__(
        self,
        *,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___DownlinkCapacity = DownlinkCapacity

@typing.final
class WriteBuffer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIZE_FIELD_NUMBER: builtins.int
    size: builtins.int
    """Buffer size in bytes."""
    def __init__(
        self,
        *,
        size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["size", b"size"]) -> None: ...

global___WriteBuffer = WriteBuffer

@typing.final
class ReadBuffer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIZE_FIELD_NUMBER: builtins.int
    size: builtins.int
    """Buffer size in bytes."""
    def __init__(
        self,
        *,
        size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["size", b"size"]) -> None: ...

global___ReadBuffer = ReadBuffer

@typing.final
class ConnectionReuse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLE_FIELD_NUMBER: builtins.int
    enable: builtins.bool
    def __init__(
        self,
        *,
        enable: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enable", b"enable"]) -> None: ...

global___ConnectionReuse = ConnectionReuse

@typing.final
class EncryptionSeed(google.protobuf.message.Message):
    """Pre-shared secret between client and server. It is used for traffic obfuscation.
    Note that if seed is absent in the config, the traffic will still be obfuscated,
    but by a predefined algorithm.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEED_FIELD_NUMBER: builtins.int
    seed: builtins.str
    def __init__(
        self,
        *,
        seed: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["seed", b"seed"]) -> None: ...

global___EncryptionSeed = EncryptionSeed

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MTU_FIELD_NUMBER: builtins.int
    TTI_FIELD_NUMBER: builtins.int
    UPLINK_CAPACITY_FIELD_NUMBER: builtins.int
    DOWNLINK_CAPACITY_FIELD_NUMBER: builtins.int
    CONGESTION_FIELD_NUMBER: builtins.int
    WRITE_BUFFER_FIELD_NUMBER: builtins.int
    READ_BUFFER_FIELD_NUMBER: builtins.int
    HEADER_CONFIG_FIELD_NUMBER: builtins.int
    SEED_FIELD_NUMBER: builtins.int
    congestion: builtins.bool
    @property
    def mtu(self) -> global___MTU: ...
    @property
    def tti(self) -> global___TTI: ...
    @property
    def uplink_capacity(self) -> global___UplinkCapacity: ...
    @property
    def downlink_capacity(self) -> global___DownlinkCapacity: ...
    @property
    def write_buffer(self) -> global___WriteBuffer: ...
    @property
    def read_buffer(self) -> global___ReadBuffer: ...
    @property
    def header_config(self) -> common.serial.typed_message_pb2.TypedMessage: ...
    @property
    def seed(self) -> global___EncryptionSeed: ...
    def __init__(
        self,
        *,
        mtu: global___MTU | None = ...,
        tti: global___TTI | None = ...,
        uplink_capacity: global___UplinkCapacity | None = ...,
        downlink_capacity: global___DownlinkCapacity | None = ...,
        congestion: builtins.bool = ...,
        write_buffer: global___WriteBuffer | None = ...,
        read_buffer: global___ReadBuffer | None = ...,
        header_config: common.serial.typed_message_pb2.TypedMessage | None = ...,
        seed: global___EncryptionSeed | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["downlink_capacity", b"downlink_capacity", "header_config", b"header_config", "mtu", b"mtu", "read_buffer", b"read_buffer", "seed", b"seed", "tti", b"tti", "uplink_capacity", b"uplink_capacity", "write_buffer", b"write_buffer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["congestion", b"congestion", "downlink_capacity", b"downlink_capacity", "header_config", b"header_config", "mtu", b"mtu", "read_buffer", b"read_buffer", "seed", b"seed", "tti", b"tti", "uplink_capacity", b"uplink_capacity", "write_buffer", b"write_buffer"]) -> None: ...

global___Config = Config
