"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.net.network_pb2
import common.protocol.server_spec_pb2
import common.protocol.user_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _CipherType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CipherTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CipherType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _CipherType.ValueType  # 0
    AES_128_GCM: _CipherType.ValueType  # 5
    AES_256_GCM: _CipherType.ValueType  # 6
    CHACHA20_POLY1305: _CipherType.ValueType  # 7
    XCHACHA20_POLY1305: _CipherType.ValueType  # 8
    NONE: _CipherType.ValueType  # 9

class CipherType(_CipherType, metaclass=_CipherTypeEnumTypeWrapper): ...

UNKNOWN: CipherType.ValueType  # 0
AES_128_GCM: CipherType.ValueType  # 5
AES_256_GCM: CipherType.ValueType  # 6
CHACHA20_POLY1305: CipherType.ValueType  # 7
XCHACHA20_POLY1305: CipherType.ValueType  # 8
NONE: CipherType.ValueType  # 9
global___CipherType = CipherType

@typing.final
class Account(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PASSWORD_FIELD_NUMBER: builtins.int
    CIPHER_TYPE_FIELD_NUMBER: builtins.int
    IV_CHECK_FIELD_NUMBER: builtins.int
    password: builtins.str
    cipher_type: global___CipherType.ValueType
    iv_check: builtins.bool
    def __init__(
        self,
        *,
        password: builtins.str = ...,
        cipher_type: global___CipherType.ValueType = ...,
        iv_check: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cipher_type", b"cipher_type", "iv_check", b"iv_check", "password", b"password"]) -> None: ...

global___Account = Account

@typing.final
class ServerConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERS_FIELD_NUMBER: builtins.int
    NETWORK_FIELD_NUMBER: builtins.int
    @property
    def users(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.protocol.user_pb2.User]: ...
    @property
    def network(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[common.net.network_pb2.Network.ValueType]: ...
    def __init__(
        self,
        *,
        users: collections.abc.Iterable[common.protocol.user_pb2.User] | None = ...,
        network: collections.abc.Iterable[common.net.network_pb2.Network.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["network", b"network", "users", b"users"]) -> None: ...

global___ServerConfig = ServerConfig

@typing.final
class ClientConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_FIELD_NUMBER: builtins.int
    @property
    def server(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.protocol.server_spec_pb2.ServerEndpoint]: ...
    def __init__(
        self,
        *,
        server: collections.abc.Iterable[common.protocol.server_spec_pb2.ServerEndpoint] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["server", b"server"]) -> None: ...

global___ClientConfig = ClientConfig
