"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.protocol.user_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DetourConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TO_FIELD_NUMBER: builtins.int
    to: builtins.str
    def __init__(
        self,
        *,
        to: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["to", b"to"]) -> None: ...

global___DetourConfig = DetourConfig

@typing.final
class DefaultConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEVEL_FIELD_NUMBER: builtins.int
    level: builtins.int
    def __init__(
        self,
        *,
        level: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["level", b"level"]) -> None: ...

global___DefaultConfig = DefaultConfig

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_FIELD_NUMBER: builtins.int
    DEFAULT_FIELD_NUMBER: builtins.int
    DETOUR_FIELD_NUMBER: builtins.int
    @property
    def user(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.protocol.user_pb2.User]: ...
    @property
    def default(self) -> global___DefaultConfig: ...
    @property
    def detour(self) -> global___DetourConfig:
        """4 is for legacy setting"""

    def __init__(
        self,
        *,
        user: collections.abc.Iterable[common.protocol.user_pb2.User] | None = ...,
        default: global___DefaultConfig | None = ...,
        detour: global___DetourConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["default", b"default", "detour", b"detour"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["default", b"default", "detour", b"detour", "user", b"user"]) -> None: ...

global___Config = Config
