"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.net.network_pb2
import common.net.port_pb2
import common.serial.typed_message_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Domain(google.protobuf.message.Message):
    """Domain for routing decision."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Domain._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Plain: Domain._Type.ValueType  # 0
        """The value is used as is."""
        Regex: Domain._Type.ValueType  # 1
        """The value is used as a regular expression."""
        Domain: Domain._Type.ValueType  # 2
        """The value is a root domain."""
        Full: Domain._Type.ValueType  # 3
        """The value is a domain."""

    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        """Type of domain value."""

    Plain: Domain.Type.ValueType  # 0
    """The value is used as is."""
    Regex: Domain.Type.ValueType  # 1
    """The value is used as a regular expression."""
    Domain: Domain.Type.ValueType  # 2
    """The value is a root domain."""
    Full: Domain.Type.ValueType  # 3
    """The value is a domain."""

    @typing.final
    class Attribute(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        BOOL_VALUE_FIELD_NUMBER: builtins.int
        INT_VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        bool_value: builtins.bool
        int_value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            bool_value: builtins.bool = ...,
            int_value: builtins.int = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["bool_value", b"bool_value", "int_value", b"int_value", "typed_value", b"typed_value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["bool_value", b"bool_value", "int_value", b"int_value", "key", b"key", "typed_value", b"typed_value"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["typed_value", b"typed_value"]) -> typing.Literal["bool_value", "int_value"] | None: ...

    TYPE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    ATTRIBUTE_FIELD_NUMBER: builtins.int
    type: global___Domain.Type.ValueType
    """Domain matching type."""
    value: builtins.str
    """Domain value."""
    @property
    def attribute(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Domain.Attribute]:
        """Attributes of this domain. May be used for filtering."""

    def __init__(
        self,
        *,
        type: global___Domain.Type.ValueType = ...,
        value: builtins.str = ...,
        attribute: collections.abc.Iterable[global___Domain.Attribute] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["attribute", b"attribute", "type", b"type", "value", b"value"]) -> None: ...

global___Domain = Domain

@typing.final
class CIDR(google.protobuf.message.Message):
    """IP for routing decision, in CIDR form."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IP_FIELD_NUMBER: builtins.int
    PREFIX_FIELD_NUMBER: builtins.int
    ip: builtins.bytes
    """IP address, should be either 4 or 16 bytes."""
    prefix: builtins.int
    """Number of leading ones in the network mask."""
    def __init__(
        self,
        *,
        ip: builtins.bytes = ...,
        prefix: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ip", b"ip", "prefix", b"prefix"]) -> None: ...

global___CIDR = CIDR

@typing.final
class GeoIP(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COUNTRY_CODE_FIELD_NUMBER: builtins.int
    CIDR_FIELD_NUMBER: builtins.int
    REVERSE_MATCH_FIELD_NUMBER: builtins.int
    country_code: builtins.str
    reverse_match: builtins.bool
    @property
    def cidr(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CIDR]: ...
    def __init__(
        self,
        *,
        country_code: builtins.str = ...,
        cidr: collections.abc.Iterable[global___CIDR] | None = ...,
        reverse_match: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cidr", b"cidr", "country_code", b"country_code", "reverse_match", b"reverse_match"]) -> None: ...

global___GeoIP = GeoIP

@typing.final
class GeoIPList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRY_FIELD_NUMBER: builtins.int
    @property
    def entry(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GeoIP]: ...
    def __init__(
        self,
        *,
        entry: collections.abc.Iterable[global___GeoIP] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["entry", b"entry"]) -> None: ...

global___GeoIPList = GeoIPList

@typing.final
class GeoSite(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COUNTRY_CODE_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    country_code: builtins.str
    @property
    def domain(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Domain]: ...
    def __init__(
        self,
        *,
        country_code: builtins.str = ...,
        domain: collections.abc.Iterable[global___Domain] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["country_code", b"country_code", "domain", b"domain"]) -> None: ...

global___GeoSite = GeoSite

@typing.final
class GeoSiteList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRY_FIELD_NUMBER: builtins.int
    @property
    def entry(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GeoSite]: ...
    def __init__(
        self,
        *,
        entry: collections.abc.Iterable[global___GeoSite] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["entry", b"entry"]) -> None: ...

global___GeoSiteList = GeoSiteList

@typing.final
class RoutingRule(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class AttributesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    TAG_FIELD_NUMBER: builtins.int
    BALANCING_TAG_FIELD_NUMBER: builtins.int
    RULE_TAG_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    GEOIP_FIELD_NUMBER: builtins.int
    PORT_LIST_FIELD_NUMBER: builtins.int
    NETWORKS_FIELD_NUMBER: builtins.int
    SOURCE_GEOIP_FIELD_NUMBER: builtins.int
    SOURCE_PORT_LIST_FIELD_NUMBER: builtins.int
    USER_EMAIL_FIELD_NUMBER: builtins.int
    INBOUND_TAG_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    LOCAL_GEOIP_FIELD_NUMBER: builtins.int
    LOCAL_PORT_LIST_FIELD_NUMBER: builtins.int
    VLESS_ROUTE_LIST_FIELD_NUMBER: builtins.int
    tag: builtins.str
    """Tag of outbound that this rule is pointing to."""
    balancing_tag: builtins.str
    """Tag of routing balancer."""
    rule_tag: builtins.str
    @property
    def domain(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Domain]:
        """List of domains for target domain matching."""

    @property
    def geoip(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GeoIP]:
        """List of GeoIPs for target IP address matching. If this entry exists, the
        cidr above will have no effect. GeoIP fields with the same country code are
        supposed to contain exactly same content. They will be merged during
        runtime. For customized GeoIPs, please leave country code empty.
        """

    @property
    def port_list(self) -> common.net.port_pb2.PortList:
        """List of ports."""

    @property
    def networks(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[common.net.network_pb2.Network.ValueType]:
        """List of networks for matching."""

    @property
    def source_geoip(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GeoIP]:
        """List of GeoIPs for source IP address matching. If this entry exists, the
        source_cidr above will have no effect.
        """

    @property
    def source_port_list(self) -> common.net.port_pb2.PortList:
        """List of ports for source port matching."""

    @property
    def user_email(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def inbound_tag(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def protocol(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def attributes(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def local_geoip(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GeoIP]: ...
    @property
    def local_port_list(self) -> common.net.port_pb2.PortList: ...
    @property
    def vless_route_list(self) -> common.net.port_pb2.PortList: ...
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        balancing_tag: builtins.str = ...,
        rule_tag: builtins.str = ...,
        domain: collections.abc.Iterable[global___Domain] | None = ...,
        geoip: collections.abc.Iterable[global___GeoIP] | None = ...,
        port_list: common.net.port_pb2.PortList | None = ...,
        networks: collections.abc.Iterable[common.net.network_pb2.Network.ValueType] | None = ...,
        source_geoip: collections.abc.Iterable[global___GeoIP] | None = ...,
        source_port_list: common.net.port_pb2.PortList | None = ...,
        user_email: collections.abc.Iterable[builtins.str] | None = ...,
        inbound_tag: collections.abc.Iterable[builtins.str] | None = ...,
        protocol: collections.abc.Iterable[builtins.str] | None = ...,
        attributes: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        local_geoip: collections.abc.Iterable[global___GeoIP] | None = ...,
        local_port_list: common.net.port_pb2.PortList | None = ...,
        vless_route_list: common.net.port_pb2.PortList | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["balancing_tag", b"balancing_tag", "local_port_list", b"local_port_list", "port_list", b"port_list", "source_port_list", b"source_port_list", "tag", b"tag", "target_tag", b"target_tag", "vless_route_list", b"vless_route_list"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["attributes", b"attributes", "balancing_tag", b"balancing_tag", "domain", b"domain", "geoip", b"geoip", "inbound_tag", b"inbound_tag", "local_geoip", b"local_geoip", "local_port_list", b"local_port_list", "networks", b"networks", "port_list", b"port_list", "protocol", b"protocol", "rule_tag", b"rule_tag", "source_geoip", b"source_geoip", "source_port_list", b"source_port_list", "tag", b"tag", "target_tag", b"target_tag", "user_email", b"user_email", "vless_route_list", b"vless_route_list"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["target_tag", b"target_tag"]) -> typing.Literal["tag", "balancing_tag"] | None: ...

global___RoutingRule = RoutingRule

@typing.final
class BalancingRule(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    OUTBOUND_SELECTOR_FIELD_NUMBER: builtins.int
    STRATEGY_FIELD_NUMBER: builtins.int
    STRATEGY_SETTINGS_FIELD_NUMBER: builtins.int
    FALLBACK_TAG_FIELD_NUMBER: builtins.int
    tag: builtins.str
    strategy: builtins.str
    fallback_tag: builtins.str
    @property
    def outbound_selector(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def strategy_settings(self) -> common.serial.typed_message_pb2.TypedMessage: ...
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        outbound_selector: collections.abc.Iterable[builtins.str] | None = ...,
        strategy: builtins.str = ...,
        strategy_settings: common.serial.typed_message_pb2.TypedMessage | None = ...,
        fallback_tag: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["strategy_settings", b"strategy_settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fallback_tag", b"fallback_tag", "outbound_selector", b"outbound_selector", "strategy", b"strategy", "strategy_settings", b"strategy_settings", "tag", b"tag"]) -> None: ...

global___BalancingRule = BalancingRule

@typing.final
class StrategyWeight(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REGEXP_FIELD_NUMBER: builtins.int
    MATCH_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    regexp: builtins.bool
    match: builtins.str
    value: builtins.float
    def __init__(
        self,
        *,
        regexp: builtins.bool = ...,
        match: builtins.str = ...,
        value: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["match", b"match", "regexp", b"regexp", "value", b"value"]) -> None: ...

global___StrategyWeight = StrategyWeight

@typing.final
class StrategyLeastLoadConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COSTS_FIELD_NUMBER: builtins.int
    BASELINES_FIELD_NUMBER: builtins.int
    EXPECTED_FIELD_NUMBER: builtins.int
    MAXRTT_FIELD_NUMBER: builtins.int
    TOLERANCE_FIELD_NUMBER: builtins.int
    expected: builtins.int
    """expected nodes count to select"""
    maxRTT: builtins.int
    """max acceptable rtt, filter away high delay nodes. default 0"""
    tolerance: builtins.float
    """acceptable failure rate"""
    @property
    def costs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StrategyWeight]:
        """weight settings"""

    @property
    def baselines(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """RTT baselines for selecting, int64 values of time.Duration"""

    def __init__(
        self,
        *,
        costs: collections.abc.Iterable[global___StrategyWeight] | None = ...,
        baselines: collections.abc.Iterable[builtins.int] | None = ...,
        expected: builtins.int = ...,
        maxRTT: builtins.int = ...,
        tolerance: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["baselines", b"baselines", "costs", b"costs", "expected", b"expected", "maxRTT", b"maxRTT", "tolerance", b"tolerance"]) -> None: ...

global___StrategyLeastLoadConfig = StrategyLeastLoadConfig

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _DomainStrategy:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DomainStrategyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Config._DomainStrategy.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        AsIs: Config._DomainStrategy.ValueType  # 0
        """Use domain as is."""
        UseIp: Config._DomainStrategy.ValueType  # 1
        """Always resolve IP for domains."""
        IpIfNonMatch: Config._DomainStrategy.ValueType  # 2
        """Resolve to IP if the domain doesn't match any rules."""
        IpOnDemand: Config._DomainStrategy.ValueType  # 3
        """Resolve to IP if any rule requires IP matching."""

    class DomainStrategy(_DomainStrategy, metaclass=_DomainStrategyEnumTypeWrapper): ...
    AsIs: Config.DomainStrategy.ValueType  # 0
    """Use domain as is."""
    UseIp: Config.DomainStrategy.ValueType  # 1
    """Always resolve IP for domains."""
    IpIfNonMatch: Config.DomainStrategy.ValueType  # 2
    """Resolve to IP if the domain doesn't match any rules."""
    IpOnDemand: Config.DomainStrategy.ValueType  # 3
    """Resolve to IP if any rule requires IP matching."""

    DOMAIN_STRATEGY_FIELD_NUMBER: builtins.int
    RULE_FIELD_NUMBER: builtins.int
    BALANCING_RULE_FIELD_NUMBER: builtins.int
    domain_strategy: global___Config.DomainStrategy.ValueType
    @property
    def rule(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RoutingRule]: ...
    @property
    def balancing_rule(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BalancingRule]: ...
    def __init__(
        self,
        *,
        domain_strategy: global___Config.DomainStrategy.ValueType = ...,
        rule: collections.abc.Iterable[global___RoutingRule] | None = ...,
        balancing_rule: collections.abc.Iterable[global___BalancingRule] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["balancing_rule", b"balancing_rule", "domain_strategy", b"domain_strategy", "rule", b"rule"]) -> None: ...

global___Config = Config
