"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class HeaderEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    HOST_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    HEADER_FIELD_NUMBER: builtins.int
    ACCEPT_PROXY_PROTOCOL_FIELD_NUMBER: builtins.int
    ED_FIELD_NUMBER: builtins.int
    HEARTBEATPERIOD_FIELD_NUMBER: builtins.int
    host: builtins.str
    path: builtins.str
    """URL path to the WebSocket service. Empty value means root(/)."""
    accept_proxy_protocol: builtins.bool
    ed: builtins.int
    heartbeatPeriod: builtins.int
    @property
    def header(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        host: builtins.str = ...,
        path: builtins.str = ...,
        header: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        accept_proxy_protocol: builtins.bool = ...,
        ed: builtins.int = ...,
        heartbeatPeriod: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accept_proxy_protocol", b"accept_proxy_protocol", "ed", b"ed", "header", b"header", "heartbeatPeriod", b"heartbeatPeriod", "host", b"host", "path", b"path"]) -> None: ...

global___Config = Config
