"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import app.router.config_pb2
import builtins
import collections.abc
import common.net.destination_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DomainMatchingType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DomainMatchingTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DomainMatchingType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Full: _DomainMatchingType.ValueType  # 0
    Subdomain: _DomainMatchingType.ValueType  # 1
    Keyword: _DomainMatchingType.ValueType  # 2
    Regex: _DomainMatchingType.ValueType  # 3

class DomainMatchingType(_DomainMatchingType, metaclass=_DomainMatchingTypeEnumTypeWrapper): ...

Full: DomainMatchingType.ValueType  # 0
Subdomain: DomainMatchingType.ValueType  # 1
Keyword: DomainMatchingType.ValueType  # 2
Regex: DomainMatchingType.ValueType  # 3
global___DomainMatchingType = DomainMatchingType

class _QueryStrategy:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _QueryStrategyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_QueryStrategy.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    USE_IP: _QueryStrategy.ValueType  # 0
    USE_IP4: _QueryStrategy.ValueType  # 1
    USE_IP6: _QueryStrategy.ValueType  # 2
    USE_SYS: _QueryStrategy.ValueType  # 3

class QueryStrategy(_QueryStrategy, metaclass=_QueryStrategyEnumTypeWrapper): ...

USE_IP: QueryStrategy.ValueType  # 0
USE_IP4: QueryStrategy.ValueType  # 1
USE_IP6: QueryStrategy.ValueType  # 2
USE_SYS: QueryStrategy.ValueType  # 3
global___QueryStrategy = QueryStrategy

@typing.final
class NameServer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class PriorityDomain(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TYPE_FIELD_NUMBER: builtins.int
        DOMAIN_FIELD_NUMBER: builtins.int
        type: global___DomainMatchingType.ValueType
        domain: builtins.str
        def __init__(
            self,
            *,
            type: global___DomainMatchingType.ValueType = ...,
            domain: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["domain", b"domain", "type", b"type"]) -> None: ...

    @typing.final
    class OriginalRule(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        RULE_FIELD_NUMBER: builtins.int
        SIZE_FIELD_NUMBER: builtins.int
        rule: builtins.str
        size: builtins.int
        def __init__(
            self,
            *,
            rule: builtins.str = ...,
            size: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["rule", b"rule", "size", b"size"]) -> None: ...

    ADDRESS_FIELD_NUMBER: builtins.int
    CLIENT_IP_FIELD_NUMBER: builtins.int
    SKIPFALLBACK_FIELD_NUMBER: builtins.int
    PRIORITIZED_DOMAIN_FIELD_NUMBER: builtins.int
    EXPECTED_GEOIP_FIELD_NUMBER: builtins.int
    ORIGINAL_RULES_FIELD_NUMBER: builtins.int
    QUERY_STRATEGY_FIELD_NUMBER: builtins.int
    ACTPRIOR_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    TIMEOUTMS_FIELD_NUMBER: builtins.int
    DISABLECACHE_FIELD_NUMBER: builtins.int
    FINALQUERY_FIELD_NUMBER: builtins.int
    UNEXPECTED_GEOIP_FIELD_NUMBER: builtins.int
    ACTUNPRIOR_FIELD_NUMBER: builtins.int
    client_ip: builtins.bytes
    skipFallback: builtins.bool
    query_strategy: global___QueryStrategy.ValueType
    actPrior: builtins.bool
    tag: builtins.str
    timeoutMs: builtins.int
    disableCache: builtins.bool
    finalQuery: builtins.bool
    actUnprior: builtins.bool
    @property
    def address(self) -> common.net.destination_pb2.Endpoint: ...
    @property
    def prioritized_domain(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NameServer.PriorityDomain]: ...
    @property
    def expected_geoip(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[app.router.config_pb2.GeoIP]: ...
    @property
    def original_rules(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NameServer.OriginalRule]: ...
    @property
    def unexpected_geoip(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[app.router.config_pb2.GeoIP]: ...
    def __init__(
        self,
        *,
        address: common.net.destination_pb2.Endpoint | None = ...,
        client_ip: builtins.bytes = ...,
        skipFallback: builtins.bool = ...,
        prioritized_domain: collections.abc.Iterable[global___NameServer.PriorityDomain] | None = ...,
        expected_geoip: collections.abc.Iterable[app.router.config_pb2.GeoIP] | None = ...,
        original_rules: collections.abc.Iterable[global___NameServer.OriginalRule] | None = ...,
        query_strategy: global___QueryStrategy.ValueType = ...,
        actPrior: builtins.bool = ...,
        tag: builtins.str = ...,
        timeoutMs: builtins.int = ...,
        disableCache: builtins.bool = ...,
        finalQuery: builtins.bool = ...,
        unexpected_geoip: collections.abc.Iterable[app.router.config_pb2.GeoIP] | None = ...,
        actUnprior: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["actPrior", b"actPrior", "actUnprior", b"actUnprior", "address", b"address", "client_ip", b"client_ip", "disableCache", b"disableCache", "expected_geoip", b"expected_geoip", "finalQuery", b"finalQuery", "original_rules", b"original_rules", "prioritized_domain", b"prioritized_domain", "query_strategy", b"query_strategy", "skipFallback", b"skipFallback", "tag", b"tag", "timeoutMs", b"timeoutMs", "unexpected_geoip", b"unexpected_geoip"]) -> None: ...

global___NameServer = NameServer

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class HostMapping(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TYPE_FIELD_NUMBER: builtins.int
        DOMAIN_FIELD_NUMBER: builtins.int
        IP_FIELD_NUMBER: builtins.int
        PROXIED_DOMAIN_FIELD_NUMBER: builtins.int
        type: global___DomainMatchingType.ValueType
        domain: builtins.str
        proxied_domain: builtins.str
        """ProxiedDomain indicates the mapped domain has the same IP address on this
        domain. Xray will use this domain for IP queries.
        """
        @property
        def ip(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
        def __init__(
            self,
            *,
            type: global___DomainMatchingType.ValueType = ...,
            domain: builtins.str = ...,
            ip: collections.abc.Iterable[builtins.bytes] | None = ...,
            proxied_domain: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["domain", b"domain", "ip", b"ip", "proxied_domain", b"proxied_domain", "type", b"type"]) -> None: ...

    NAME_SERVER_FIELD_NUMBER: builtins.int
    CLIENT_IP_FIELD_NUMBER: builtins.int
    STATIC_HOSTS_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    DISABLECACHE_FIELD_NUMBER: builtins.int
    QUERY_STRATEGY_FIELD_NUMBER: builtins.int
    DISABLEFALLBACK_FIELD_NUMBER: builtins.int
    DISABLEFALLBACKIFMATCH_FIELD_NUMBER: builtins.int
    client_ip: builtins.bytes
    """Client IP for EDNS client subnet. Must be 4 bytes (IPv4) or 16 bytes
    (IPv6).
    """
    tag: builtins.str
    """Tag is the inbound tag of DNS client."""
    disableCache: builtins.bool
    """DisableCache disables DNS cache"""
    query_strategy: global___QueryStrategy.ValueType
    disableFallback: builtins.bool
    disableFallbackIfMatch: builtins.bool
    @property
    def name_server(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NameServer]:
        """NameServer list used by this DNS client.
        A special value 'localhost' as a domain address can be set to use DNS on local system.
        """

    @property
    def static_hosts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Config.HostMapping]: ...
    def __init__(
        self,
        *,
        name_server: collections.abc.Iterable[global___NameServer] | None = ...,
        client_ip: builtins.bytes = ...,
        static_hosts: collections.abc.Iterable[global___Config.HostMapping] | None = ...,
        tag: builtins.str = ...,
        disableCache: builtins.bool = ...,
        query_strategy: global___QueryStrategy.ValueType = ...,
        disableFallback: builtins.bool = ...,
        disableFallbackIfMatch: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_ip", b"client_ip", "disableCache", b"disableCache", "disableFallback", b"disableFallback", "disableFallbackIfMatch", b"disableFallbackIfMatch", "name_server", b"name_server", "query_strategy", b"query_strategy", "static_hosts", b"static_hosts", "tag", b"tag"]) -> None: ...

global___Config = Config
