"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ObservationResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    @property
    def status(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OutboundStatus]: ...
    def __init__(
        self,
        *,
        status: collections.abc.Iterable[global___OutboundStatus] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___ObservationResult = ObservationResult

@typing.final
class HealthPingMeasurementResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALL_FIELD_NUMBER: builtins.int
    FAIL_FIELD_NUMBER: builtins.int
    DEVIATION_FIELD_NUMBER: builtins.int
    AVERAGE_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    MIN_FIELD_NUMBER: builtins.int
    all: builtins.int
    fail: builtins.int
    deviation: builtins.int
    average: builtins.int
    max: builtins.int
    min: builtins.int
    def __init__(
        self,
        *,
        all: builtins.int = ...,
        fail: builtins.int = ...,
        deviation: builtins.int = ...,
        average: builtins.int = ...,
        max: builtins.int = ...,
        min: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["all", b"all", "average", b"average", "deviation", b"deviation", "fail", b"fail", "max", b"max", "min", b"min"]) -> None: ...

global___HealthPingMeasurementResult = HealthPingMeasurementResult

@typing.final
class OutboundStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALIVE_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    LAST_ERROR_REASON_FIELD_NUMBER: builtins.int
    OUTBOUND_TAG_FIELD_NUMBER: builtins.int
    LAST_SEEN_TIME_FIELD_NUMBER: builtins.int
    LAST_TRY_TIME_FIELD_NUMBER: builtins.int
    HEALTH_PING_FIELD_NUMBER: builtins.int
    alive: builtins.bool
    """@Document Whether this outbound is usable
    @Restriction ReadOnlyForUser
    """
    delay: builtins.int
    """@Document The time for probe request to finish.
    @Type time.ms
    @Restriction ReadOnlyForUser
    """
    last_error_reason: builtins.str
    """@Document The last error caused this outbound failed to relay probe request
    @Restriction NotMachineReadable
    """
    outbound_tag: builtins.str
    """@Document The outbound tag for this Server
    @Type id.outboundTag
    """
    last_seen_time: builtins.int
    """@Document The time this outbound is known to be alive
    @Type id.outboundTag
    """
    last_try_time: builtins.int
    """@Document The time this outbound is tried
    @Type id.outboundTag
    """
    @property
    def health_ping(self) -> global___HealthPingMeasurementResult: ...
    def __init__(
        self,
        *,
        alive: builtins.bool = ...,
        delay: builtins.int = ...,
        last_error_reason: builtins.str = ...,
        outbound_tag: builtins.str = ...,
        last_seen_time: builtins.int = ...,
        last_try_time: builtins.int = ...,
        health_ping: global___HealthPingMeasurementResult | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["health_ping", b"health_ping"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["alive", b"alive", "delay", b"delay", "health_ping", b"health_ping", "last_error_reason", b"last_error_reason", "last_seen_time", b"last_seen_time", "last_try_time", b"last_try_time", "outbound_tag", b"outbound_tag"]) -> None: ...

global___OutboundStatus = OutboundStatus

@typing.final
class ProbeResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALIVE_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    LAST_ERROR_REASON_FIELD_NUMBER: builtins.int
    alive: builtins.bool
    """@Document Whether this outbound is usable
    @Restriction ReadOnlyForUser
    """
    delay: builtins.int
    """@Document The time for probe request to finish.
    @Type time.ms
    @Restriction ReadOnlyForUser
    """
    last_error_reason: builtins.str
    """@Document The error caused this outbound failed to relay probe request
    @Restriction NotMachineReadable
    """
    def __init__(
        self,
        *,
        alive: builtins.bool = ...,
        delay: builtins.int = ...,
        last_error_reason: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["alive", b"alive", "delay", b"delay", "last_error_reason", b"last_error_reason"]) -> None: ...

global___ProbeResult = ProbeResult

@typing.final
class Intensity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROBE_INTERVAL_FIELD_NUMBER: builtins.int
    probe_interval: builtins.int
    """@Document The time interval for a probe request in ms.
    @Type time.ms
    """
    def __init__(
        self,
        *,
        probe_interval: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["probe_interval", b"probe_interval"]) -> None: ...

global___Intensity = Intensity

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBJECT_SELECTOR_FIELD_NUMBER: builtins.int
    PROBE_URL_FIELD_NUMBER: builtins.int
    PROBE_INTERVAL_FIELD_NUMBER: builtins.int
    ENABLE_CONCURRENCY_FIELD_NUMBER: builtins.int
    probe_url: builtins.str
    probe_interval: builtins.int
    enable_concurrency: builtins.bool
    @property
    def subject_selector(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """@Document The selectors for outbound under observation"""

    def __init__(
        self,
        *,
        subject_selector: collections.abc.Iterable[builtins.str] | None = ...,
        probe_url: builtins.str = ...,
        probe_interval: builtins.int = ...,
        enable_concurrency: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enable_concurrency", b"enable_concurrency", "probe_interval", b"probe_interval", "probe_url", b"probe_url", "subject_selector", b"subject_selector"]) -> None: ...

global___Config = Config
