"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.net.address_pb2
import common.net.network_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class PortMapEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ADDRESS_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    PORT_MAP_FIELD_NUMBER: builtins.int
    NETWORKS_FIELD_NUMBER: builtins.int
    FOLLOW_REDIRECT_FIELD_NUMBER: builtins.int
    USER_LEVEL_FIELD_NUMBER: builtins.int
    port: builtins.int
    follow_redirect: builtins.bool
    user_level: builtins.int
    @property
    def address(self) -> common.net.address_pb2.IPOrDomain: ...
    @property
    def port_map(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def networks(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[common.net.network_pb2.Network.ValueType]:
        """List of networks that the Dokodemo accepts."""

    def __init__(
        self,
        *,
        address: common.net.address_pb2.IPOrDomain | None = ...,
        port: builtins.int = ...,
        port_map: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        networks: collections.abc.Iterable[common.net.network_pb2.Network.ValueType] | None = ...,
        follow_redirect: builtins.bool = ...,
        user_level: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "follow_redirect", b"follow_redirect", "networks", b"networks", "port", b"port", "port_map", b"port_map", "user_level", b"user_level"]) -> None: ...

global___Config = Config
