"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.net.address_pb2
import common.serial.typed_message_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DomainStrategy:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DomainStrategyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DomainStrategy.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    AS_IS: _DomainStrategy.ValueType  # 0
    USE_IP: _DomainStrategy.ValueType  # 1
    USE_IP4: _DomainStrategy.ValueType  # 2
    USE_IP6: _DomainStrategy.ValueType  # 3
    USE_IP46: _DomainStrategy.ValueType  # 4
    USE_IP64: _DomainStrategy.ValueType  # 5
    FORCE_IP: _DomainStrategy.ValueType  # 6
    FORCE_IP4: _DomainStrategy.ValueType  # 7
    FORCE_IP6: _DomainStrategy.ValueType  # 8
    FORCE_IP46: _DomainStrategy.ValueType  # 9
    FORCE_IP64: _DomainStrategy.ValueType  # 10

class DomainStrategy(_DomainStrategy, metaclass=_DomainStrategyEnumTypeWrapper): ...

AS_IS: DomainStrategy.ValueType  # 0
USE_IP: DomainStrategy.ValueType  # 1
USE_IP4: DomainStrategy.ValueType  # 2
USE_IP6: DomainStrategy.ValueType  # 3
USE_IP46: DomainStrategy.ValueType  # 4
USE_IP64: DomainStrategy.ValueType  # 5
FORCE_IP: DomainStrategy.ValueType  # 6
FORCE_IP4: DomainStrategy.ValueType  # 7
FORCE_IP6: DomainStrategy.ValueType  # 8
FORCE_IP46: DomainStrategy.ValueType  # 9
FORCE_IP64: DomainStrategy.ValueType  # 10
global___DomainStrategy = DomainStrategy

class _AddressPortStrategy:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AddressPortStrategyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AddressPortStrategy.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SrvPortOnly: _AddressPortStrategy.ValueType  # 1
    SrvAddressOnly: _AddressPortStrategy.ValueType  # 2
    SrvPortAndAddress: _AddressPortStrategy.ValueType  # 3
    TxtPortOnly: _AddressPortStrategy.ValueType  # 4
    TxtAddressOnly: _AddressPortStrategy.ValueType  # 5
    TxtPortAndAddress: _AddressPortStrategy.ValueType  # 6

class AddressPortStrategy(_AddressPortStrategy, metaclass=_AddressPortStrategyEnumTypeWrapper): ...

SrvPortOnly: AddressPortStrategy.ValueType  # 1
SrvAddressOnly: AddressPortStrategy.ValueType  # 2
SrvPortAndAddress: AddressPortStrategy.ValueType  # 3
TxtPortOnly: AddressPortStrategy.ValueType  # 4
TxtAddressOnly: AddressPortStrategy.ValueType  # 5
TxtPortAndAddress: AddressPortStrategy.ValueType  # 6
global___AddressPortStrategy = AddressPortStrategy

@typing.final
class TransportConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROTOCOL_NAME_FIELD_NUMBER: builtins.int
    SETTINGS_FIELD_NUMBER: builtins.int
    protocol_name: builtins.str
    """Transport protocol name."""
    @property
    def settings(self) -> common.serial.typed_message_pb2.TypedMessage:
        """Specific transport protocol settings."""

    def __init__(
        self,
        *,
        protocol_name: builtins.str = ...,
        settings: common.serial.typed_message_pb2.TypedMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["settings", b"settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["protocol_name", b"protocol_name", "settings", b"settings"]) -> None: ...

global___TransportConfig = TransportConfig

@typing.final
class StreamConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    PROTOCOL_NAME_FIELD_NUMBER: builtins.int
    TRANSPORT_SETTINGS_FIELD_NUMBER: builtins.int
    SECURITY_TYPE_FIELD_NUMBER: builtins.int
    SECURITY_SETTINGS_FIELD_NUMBER: builtins.int
    SOCKET_SETTINGS_FIELD_NUMBER: builtins.int
    port: builtins.int
    protocol_name: builtins.str
    """Effective network."""
    security_type: builtins.str
    """Type of security. Must be a message name of the settings proto."""
    @property
    def address(self) -> common.net.address_pb2.IPOrDomain: ...
    @property
    def transport_settings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TransportConfig]: ...
    @property
    def security_settings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.serial.typed_message_pb2.TypedMessage]:
        """Transport security settings. They can be either TLS or REALITY."""

    @property
    def socket_settings(self) -> global___SocketConfig: ...
    def __init__(
        self,
        *,
        address: common.net.address_pb2.IPOrDomain | None = ...,
        port: builtins.int = ...,
        protocol_name: builtins.str = ...,
        transport_settings: collections.abc.Iterable[global___TransportConfig] | None = ...,
        security_type: builtins.str = ...,
        security_settings: collections.abc.Iterable[common.serial.typed_message_pb2.TypedMessage] | None = ...,
        socket_settings: global___SocketConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address", "socket_settings", b"socket_settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "port", b"port", "protocol_name", b"protocol_name", "security_settings", b"security_settings", "security_type", b"security_type", "socket_settings", b"socket_settings", "transport_settings", b"transport_settings"]) -> None: ...

global___StreamConfig = StreamConfig

@typing.final
class ProxyConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    TRANSPORTLAYERPROXY_FIELD_NUMBER: builtins.int
    tag: builtins.str
    transportLayerProxy: builtins.bool
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        transportLayerProxy: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["tag", b"tag", "transportLayerProxy", b"transportLayerProxy"]) -> None: ...

global___ProxyConfig = ProxyConfig

@typing.final
class CustomSockopt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYSTEM_FIELD_NUMBER: builtins.int
    NETWORK_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    OPT_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    system: builtins.str
    network: builtins.str
    level: builtins.str
    opt: builtins.str
    value: builtins.str
    type: builtins.str
    def __init__(
        self,
        *,
        system: builtins.str = ...,
        network: builtins.str = ...,
        level: builtins.str = ...,
        opt: builtins.str = ...,
        value: builtins.str = ...,
        type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["level", b"level", "network", b"network", "opt", b"opt", "system", b"system", "type", b"type", "value", b"value"]) -> None: ...

global___CustomSockopt = CustomSockopt

@typing.final
class SocketConfig(google.protobuf.message.Message):
    """SocketConfig is options to be applied on network sockets."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TProxyMode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TProxyModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SocketConfig._TProxyMode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Off: SocketConfig._TProxyMode.ValueType  # 0
        """TProxy is off."""
        TProxy: SocketConfig._TProxyMode.ValueType  # 1
        """TProxy mode."""
        Redirect: SocketConfig._TProxyMode.ValueType  # 2
        """Redirect mode."""

    class TProxyMode(_TProxyMode, metaclass=_TProxyModeEnumTypeWrapper): ...
    Off: SocketConfig.TProxyMode.ValueType  # 0
    """TProxy is off."""
    TProxy: SocketConfig.TProxyMode.ValueType  # 1
    """TProxy mode."""
    Redirect: SocketConfig.TProxyMode.ValueType  # 2
    """Redirect mode."""

    MARK_FIELD_NUMBER: builtins.int
    TFO_FIELD_NUMBER: builtins.int
    TPROXY_FIELD_NUMBER: builtins.int
    RECEIVE_ORIGINAL_DEST_ADDRESS_FIELD_NUMBER: builtins.int
    BIND_ADDRESS_FIELD_NUMBER: builtins.int
    BIND_PORT_FIELD_NUMBER: builtins.int
    ACCEPT_PROXY_PROTOCOL_FIELD_NUMBER: builtins.int
    DOMAIN_STRATEGY_FIELD_NUMBER: builtins.int
    DIALER_PROXY_FIELD_NUMBER: builtins.int
    TCP_KEEP_ALIVE_INTERVAL_FIELD_NUMBER: builtins.int
    TCP_KEEP_ALIVE_IDLE_FIELD_NUMBER: builtins.int
    TCP_CONGESTION_FIELD_NUMBER: builtins.int
    INTERFACE_FIELD_NUMBER: builtins.int
    V6ONLY_FIELD_NUMBER: builtins.int
    TCP_WINDOW_CLAMP_FIELD_NUMBER: builtins.int
    TCP_USER_TIMEOUT_FIELD_NUMBER: builtins.int
    TCP_MAX_SEG_FIELD_NUMBER: builtins.int
    PENETRATE_FIELD_NUMBER: builtins.int
    TCP_MPTCP_FIELD_NUMBER: builtins.int
    CUSTOMSOCKOPT_FIELD_NUMBER: builtins.int
    ADDRESS_PORT_STRATEGY_FIELD_NUMBER: builtins.int
    HAPPY_EYEBALLS_FIELD_NUMBER: builtins.int
    mark: builtins.int
    """Mark of the connection. If non-zero, the value will be set to SO_MARK."""
    tfo: builtins.int
    """TFO is the state of TFO settings."""
    tproxy: global___SocketConfig.TProxyMode.ValueType
    """TProxy is for enabling TProxy socket option."""
    receive_original_dest_address: builtins.bool
    """ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
    option. This option is for UDP only.
    """
    bind_address: builtins.bytes
    bind_port: builtins.int
    accept_proxy_protocol: builtins.bool
    domain_strategy: global___DomainStrategy.ValueType
    dialer_proxy: builtins.str
    tcp_keep_alive_interval: builtins.int
    tcp_keep_alive_idle: builtins.int
    tcp_congestion: builtins.str
    interface: builtins.str
    v6only: builtins.bool
    tcp_window_clamp: builtins.int
    tcp_user_timeout: builtins.int
    tcp_max_seg: builtins.int
    penetrate: builtins.bool
    tcp_mptcp: builtins.bool
    address_port_strategy: global___AddressPortStrategy.ValueType
    @property
    def customSockopt(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CustomSockopt]: ...
    @property
    def happy_eyeballs(self) -> global___HappyEyeballsConfig: ...
    def __init__(
        self,
        *,
        mark: builtins.int = ...,
        tfo: builtins.int = ...,
        tproxy: global___SocketConfig.TProxyMode.ValueType = ...,
        receive_original_dest_address: builtins.bool = ...,
        bind_address: builtins.bytes = ...,
        bind_port: builtins.int = ...,
        accept_proxy_protocol: builtins.bool = ...,
        domain_strategy: global___DomainStrategy.ValueType = ...,
        dialer_proxy: builtins.str = ...,
        tcp_keep_alive_interval: builtins.int = ...,
        tcp_keep_alive_idle: builtins.int = ...,
        tcp_congestion: builtins.str = ...,
        interface: builtins.str = ...,
        v6only: builtins.bool = ...,
        tcp_window_clamp: builtins.int = ...,
        tcp_user_timeout: builtins.int = ...,
        tcp_max_seg: builtins.int = ...,
        penetrate: builtins.bool = ...,
        tcp_mptcp: builtins.bool = ...,
        customSockopt: collections.abc.Iterable[global___CustomSockopt] | None = ...,
        address_port_strategy: global___AddressPortStrategy.ValueType = ...,
        happy_eyeballs: global___HappyEyeballsConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["happy_eyeballs", b"happy_eyeballs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["accept_proxy_protocol", b"accept_proxy_protocol", "address_port_strategy", b"address_port_strategy", "bind_address", b"bind_address", "bind_port", b"bind_port", "customSockopt", b"customSockopt", "dialer_proxy", b"dialer_proxy", "domain_strategy", b"domain_strategy", "happy_eyeballs", b"happy_eyeballs", "interface", b"interface", "mark", b"mark", "penetrate", b"penetrate", "receive_original_dest_address", b"receive_original_dest_address", "tcp_congestion", b"tcp_congestion", "tcp_keep_alive_idle", b"tcp_keep_alive_idle", "tcp_keep_alive_interval", b"tcp_keep_alive_interval", "tcp_max_seg", b"tcp_max_seg", "tcp_mptcp", b"tcp_mptcp", "tcp_user_timeout", b"tcp_user_timeout", "tcp_window_clamp", b"tcp_window_clamp", "tfo", b"tfo", "tproxy", b"tproxy", "v6only", b"v6only"]) -> None: ...

global___SocketConfig = SocketConfig

@typing.final
class HappyEyeballsConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRIORITIZE_IPV6_FIELD_NUMBER: builtins.int
    INTERLEAVE_FIELD_NUMBER: builtins.int
    TRY_DELAYMS_FIELD_NUMBER: builtins.int
    MAX_CONCURRENT_TRY_FIELD_NUMBER: builtins.int
    prioritize_ipv6: builtins.bool
    interleave: builtins.int
    try_delayMs: builtins.int
    max_concurrent_try: builtins.int
    def __init__(
        self,
        *,
        prioritize_ipv6: builtins.bool = ...,
        interleave: builtins.int = ...,
        try_delayMs: builtins.int = ...,
        max_concurrent_try: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["interleave", b"interleave", "max_concurrent_try", b"max_concurrent_try", "prioritize_ipv6", b"prioritize_ipv6", "try_delayMs", b"try_delayMs"]) -> None: ...

global___HappyEyeballsConfig = HappyEyeballsConfig
