"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: builtins.int
    SERVICE_NAME_FIELD_NUMBER: builtins.int
    MULTI_MODE_FIELD_NUMBER: builtins.int
    IDLE_TIMEOUT_FIELD_NUMBER: builtins.int
    HEALTH_CHECK_TIMEOUT_FIELD_NUMBER: builtins.int
    PERMIT_WITHOUT_STREAM_FIELD_NUMBER: builtins.int
    INITIAL_WINDOWS_SIZE_FIELD_NUMBER: builtins.int
    USER_AGENT_FIELD_NUMBER: builtins.int
    authority: builtins.str
    service_name: builtins.str
    multi_mode: builtins.bool
    idle_timeout: builtins.int
    health_check_timeout: builtins.int
    permit_without_stream: builtins.bool
    initial_windows_size: builtins.int
    user_agent: builtins.str
    def __init__(
        self,
        *,
        authority: builtins.str = ...,
        service_name: builtins.str = ...,
        multi_mode: builtins.bool = ...,
        idle_timeout: builtins.int = ...,
        health_check_timeout: builtins.int = ...,
        permit_without_stream: builtins.bool = ...,
        initial_windows_size: builtins.int = ...,
        user_agent: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["authority", b"authority", "health_check_timeout", b"health_check_timeout", "idle_timeout", b"idle_timeout", "initial_windows_size", b"initial_windows_size", "multi_mode", b"multi_mode", "permit_without_stream", b"permit_without_stream", "service_name", b"service_name", "user_agent", b"user_agent"]) -> None: ...

global___Config = Config
