"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.serial.typed_message_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    """Config is the master config of Xray. Xray takes this config as input and
    functions accordingly.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INBOUND_FIELD_NUMBER: builtins.int
    OUTBOUND_FIELD_NUMBER: builtins.int
    APP_FIELD_NUMBER: builtins.int
    EXTENSION_FIELD_NUMBER: builtins.int
    @property
    def inbound(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___InboundHandlerConfig]:
        """Inbound handler configurations. Must have at least one item."""

    @property
    def outbound(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OutboundHandlerConfig]:
        """Outbound handler configurations. Must have at least one item. The first
        item is used as default for routing.
        """

    @property
    def app(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.serial.typed_message_pb2.TypedMessage]:
        """App is for configurations of all features in Xray. A feature must
        implement the Feature interface, and its config type must be registered
        through common.RegisterConfig.
        """

    @property
    def extension(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.serial.typed_message_pb2.TypedMessage]:
        """Configuration for extensions. The config may not work if corresponding
        extension is not loaded into Xray. Xray will ignore such config during
        initialization.
        """

    def __init__(
        self,
        *,
        inbound: collections.abc.Iterable[global___InboundHandlerConfig] | None = ...,
        outbound: collections.abc.Iterable[global___OutboundHandlerConfig] | None = ...,
        app: collections.abc.Iterable[common.serial.typed_message_pb2.TypedMessage] | None = ...,
        extension: collections.abc.Iterable[common.serial.typed_message_pb2.TypedMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["app", b"app", "extension", b"extension", "inbound", b"inbound", "outbound", b"outbound"]) -> None: ...

global___Config = Config

@typing.final
class InboundHandlerConfig(google.protobuf.message.Message):
    """InboundHandlerConfig is the configuration for inbound handler."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    RECEIVER_SETTINGS_FIELD_NUMBER: builtins.int
    PROXY_SETTINGS_FIELD_NUMBER: builtins.int
    tag: builtins.str
    """Tag of the inbound handler. The tag must be unique among all inbound
    handlers
    """
    @property
    def receiver_settings(self) -> common.serial.typed_message_pb2.TypedMessage:
        """Settings for how this inbound proxy is handled."""

    @property
    def proxy_settings(self) -> common.serial.typed_message_pb2.TypedMessage:
        """Settings for inbound proxy. Must be one of the inbound proxies."""

    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        receiver_settings: common.serial.typed_message_pb2.TypedMessage | None = ...,
        proxy_settings: common.serial.typed_message_pb2.TypedMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["proxy_settings", b"proxy_settings", "receiver_settings", b"receiver_settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["proxy_settings", b"proxy_settings", "receiver_settings", b"receiver_settings", "tag", b"tag"]) -> None: ...

global___InboundHandlerConfig = InboundHandlerConfig

@typing.final
class OutboundHandlerConfig(google.protobuf.message.Message):
    """OutboundHandlerConfig is the configuration for outbound handler."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    SENDER_SETTINGS_FIELD_NUMBER: builtins.int
    PROXY_SETTINGS_FIELD_NUMBER: builtins.int
    EXPIRE_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    tag: builtins.str
    """Tag of this outbound handler."""
    expire: builtins.int
    """If not zero, this outbound will be expired in seconds. Not used for now."""
    comment: builtins.str
    """Comment of this outbound handler. Not used for now."""
    @property
    def sender_settings(self) -> common.serial.typed_message_pb2.TypedMessage:
        """Settings for how to dial connection for this outbound handler."""

    @property
    def proxy_settings(self) -> common.serial.typed_message_pb2.TypedMessage:
        """Settings for this outbound proxy. Must be one of the outbound proxies."""

    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        sender_settings: common.serial.typed_message_pb2.TypedMessage | None = ...,
        proxy_settings: common.serial.typed_message_pb2.TypedMessage | None = ...,
        expire: builtins.int = ...,
        comment: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["proxy_settings", b"proxy_settings", "sender_settings", b"sender_settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["comment", b"comment", "expire", b"expire", "proxy_settings", b"proxy_settings", "sender_settings", b"sender_settings", "tag", b"tag"]) -> None: ...

global___OutboundHandlerConfig = OutboundHandlerConfig
