"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    """Config is the settings for metrics."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    LISTEN_FIELD_NUMBER: builtins.int
    tag: builtins.str
    """Tag of the outbound handler that handles metrics http connections."""
    listen: builtins.str
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        listen: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["listen", b"listen", "tag", b"tag"]) -> None: ...

global___Config = Config
