"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common.protocol.server_spec_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import transport.internet.config_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DestinationOverride(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_FIELD_NUMBER: builtins.int
    @property
    def server(self) -> common.protocol.server_spec_pb2.ServerEndpoint: ...
    def __init__(
        self,
        *,
        server: common.protocol.server_spec_pb2.ServerEndpoint | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["server", b"server"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["server", b"server"]) -> None: ...

global___DestinationOverride = DestinationOverride

@typing.final
class Fragment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PACKETS_FROM_FIELD_NUMBER: builtins.int
    PACKETS_TO_FIELD_NUMBER: builtins.int
    LENGTH_MIN_FIELD_NUMBER: builtins.int
    LENGTH_MAX_FIELD_NUMBER: builtins.int
    INTERVAL_MIN_FIELD_NUMBER: builtins.int
    INTERVAL_MAX_FIELD_NUMBER: builtins.int
    MAX_SPLIT_MIN_FIELD_NUMBER: builtins.int
    MAX_SPLIT_MAX_FIELD_NUMBER: builtins.int
    packets_from: builtins.int
    packets_to: builtins.int
    length_min: builtins.int
    length_max: builtins.int
    interval_min: builtins.int
    interval_max: builtins.int
    max_split_min: builtins.int
    max_split_max: builtins.int
    def __init__(
        self,
        *,
        packets_from: builtins.int = ...,
        packets_to: builtins.int = ...,
        length_min: builtins.int = ...,
        length_max: builtins.int = ...,
        interval_min: builtins.int = ...,
        interval_max: builtins.int = ...,
        max_split_min: builtins.int = ...,
        max_split_max: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["interval_max", b"interval_max", "interval_min", b"interval_min", "length_max", b"length_max", "length_min", b"length_min", "max_split_max", b"max_split_max", "max_split_min", b"max_split_min", "packets_from", b"packets_from", "packets_to", b"packets_to"]) -> None: ...

global___Fragment = Fragment

@typing.final
class Noise(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LENGTH_MIN_FIELD_NUMBER: builtins.int
    LENGTH_MAX_FIELD_NUMBER: builtins.int
    DELAY_MIN_FIELD_NUMBER: builtins.int
    DELAY_MAX_FIELD_NUMBER: builtins.int
    PACKET_FIELD_NUMBER: builtins.int
    APPLY_TO_FIELD_NUMBER: builtins.int
    length_min: builtins.int
    length_max: builtins.int
    delay_min: builtins.int
    delay_max: builtins.int
    packet: builtins.bytes
    apply_to: builtins.str
    def __init__(
        self,
        *,
        length_min: builtins.int = ...,
        length_max: builtins.int = ...,
        delay_min: builtins.int = ...,
        delay_max: builtins.int = ...,
        packet: builtins.bytes = ...,
        apply_to: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["apply_to", b"apply_to", "delay_max", b"delay_max", "delay_min", b"delay_min", "length_max", b"length_max", "length_min", b"length_min", "packet", b"packet"]) -> None: ...

global___Noise = Noise

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOMAIN_STRATEGY_FIELD_NUMBER: builtins.int
    DESTINATION_OVERRIDE_FIELD_NUMBER: builtins.int
    USER_LEVEL_FIELD_NUMBER: builtins.int
    FRAGMENT_FIELD_NUMBER: builtins.int
    PROXY_PROTOCOL_FIELD_NUMBER: builtins.int
    NOISES_FIELD_NUMBER: builtins.int
    domain_strategy: transport.internet.config_pb2.DomainStrategy.ValueType
    user_level: builtins.int
    proxy_protocol: builtins.int
    @property
    def destination_override(self) -> global___DestinationOverride: ...
    @property
    def fragment(self) -> global___Fragment: ...
    @property
    def noises(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Noise]: ...
    def __init__(
        self,
        *,
        domain_strategy: transport.internet.config_pb2.DomainStrategy.ValueType = ...,
        destination_override: global___DestinationOverride | None = ...,
        user_level: builtins.int = ...,
        fragment: global___Fragment | None = ...,
        proxy_protocol: builtins.int = ...,
        noises: collections.abc.Iterable[global___Noise] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["destination_override", b"destination_override", "fragment", b"fragment"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["destination_override", b"destination_override", "domain_strategy", b"domain_strategy", "fragment", b"fragment", "noises", b"noises", "proxy_protocol", b"proxy_protocol", "user_level", b"user_level"]) -> None: ...

global___Config = Config
