"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INBOUND_TAG_FIELD_NUMBER: builtins.int
    inbound_tag: builtins.str
    def __init__(
        self,
        *,
        inbound_tag: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["inbound_tag", b"inbound_tag"]) -> None: ...

global___Config = Config
