"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CORE_VERSION_FIELD_NUMBER: builtins.int
    MIN_VERSION_FIELD_NUMBER: builtins.int
    MAX_VERSION_FIELD_NUMBER: builtins.int
    core_version: builtins.str
    min_version: builtins.str
    max_version: builtins.str
    def __init__(
        self,
        *,
        core_version: builtins.str = ...,
        min_version: builtins.str = ...,
        max_version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["core_version", b"core_version", "max_version", b"max_version", "min_version", b"min_version"]) -> None: ...

global___Config = Config
