"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import transport.internet.config_pb2
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Certificate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Usage:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _UsageEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Certificate._Usage.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ENCIPHERMENT: Certificate._Usage.ValueType  # 0
        AUTHORITY_VERIFY: Certificate._Usage.ValueType  # 1
        AUTHORITY_ISSUE: Certificate._Usage.ValueType  # 2

    class Usage(_Usage, metaclass=_UsageEnumTypeWrapper): ...
    ENCIPHERMENT: Certificate.Usage.ValueType  # 0
    AUTHORITY_VERIFY: Certificate.Usage.ValueType  # 1
    AUTHORITY_ISSUE: Certificate.Usage.ValueType  # 2

    CERTIFICATE_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    USAGE_FIELD_NUMBER: builtins.int
    OCSP_STAPLING_FIELD_NUMBER: builtins.int
    CERTIFICATE_PATH_FIELD_NUMBER: builtins.int
    KEY_PATH_FIELD_NUMBER: builtins.int
    ONE_TIME_LOADING_FIELD_NUMBER: builtins.int
    BUILD_CHAIN_FIELD_NUMBER: builtins.int
    certificate: builtins.bytes
    """TLS certificate in x509 format."""
    key: builtins.bytes
    """TLS key in x509 format."""
    usage: global___Certificate.Usage.ValueType
    ocsp_stapling: builtins.int
    certificate_path: builtins.str
    """TLS certificate path"""
    key_path: builtins.str
    """TLS Key path"""
    One_time_loading: builtins.bool
    """If true, one-Time Loading"""
    build_chain: builtins.bool
    def __init__(
        self,
        *,
        certificate: builtins.bytes = ...,
        key: builtins.bytes = ...,
        usage: global___Certificate.Usage.ValueType = ...,
        ocsp_stapling: builtins.int = ...,
        certificate_path: builtins.str = ...,
        key_path: builtins.str = ...,
        One_time_loading: builtins.bool = ...,
        build_chain: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["One_time_loading", b"One_time_loading", "build_chain", b"build_chain", "certificate", b"certificate", "certificate_path", b"certificate_path", "key", b"key", "key_path", b"key_path", "ocsp_stapling", b"ocsp_stapling", "usage", b"usage"]) -> None: ...

global___Certificate = Certificate

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALLOW_INSECURE_FIELD_NUMBER: builtins.int
    CERTIFICATE_FIELD_NUMBER: builtins.int
    SERVER_NAME_FIELD_NUMBER: builtins.int
    NEXT_PROTOCOL_FIELD_NUMBER: builtins.int
    ENABLE_SESSION_RESUMPTION_FIELD_NUMBER: builtins.int
    DISABLE_SYSTEM_ROOT_FIELD_NUMBER: builtins.int
    MIN_VERSION_FIELD_NUMBER: builtins.int
    MAX_VERSION_FIELD_NUMBER: builtins.int
    CIPHER_SUITES_FIELD_NUMBER: builtins.int
    FINGERPRINT_FIELD_NUMBER: builtins.int
    REJECT_UNKNOWN_SNI_FIELD_NUMBER: builtins.int
    PINNED_PEER_CERTIFICATE_CHAIN_SHA256_FIELD_NUMBER: builtins.int
    PINNED_PEER_CERTIFICATE_PUBLIC_KEY_SHA256_FIELD_NUMBER: builtins.int
    MASTER_KEY_LOG_FIELD_NUMBER: builtins.int
    CURVE_PREFERENCES_FIELD_NUMBER: builtins.int
    VERIFY_PEER_CERT_IN_NAMES_FIELD_NUMBER: builtins.int
    ECH_SERVER_KEYS_FIELD_NUMBER: builtins.int
    ECH_CONFIG_LIST_FIELD_NUMBER: builtins.int
    ECH_FORCE_QUERY_FIELD_NUMBER: builtins.int
    ECH_SOCKET_SETTINGS_FIELD_NUMBER: builtins.int
    allow_insecure: builtins.bool
    """Whether or not to allow self-signed certificates."""
    server_name: builtins.str
    """Override server name."""
    enable_session_resumption: builtins.bool
    """Whether or not to enable session (ticket) resumption."""
    disable_system_root: builtins.bool
    """If true, root certificates on the system will not be loaded for
    verification.
    """
    min_version: builtins.str
    """The minimum TLS version."""
    max_version: builtins.str
    """The maximum TLS version."""
    cipher_suites: builtins.str
    """Specify cipher suites, except for TLS 1.3."""
    fingerprint: builtins.str
    """TLS Client Hello fingerprint (uTLS)."""
    reject_unknown_sni: builtins.bool
    master_key_log: builtins.str
    ech_server_keys: builtins.bytes
    ech_config_list: builtins.str
    ech_force_query: builtins.str
    @property
    def certificate(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Certificate]:
        """List of certificates to be served on server."""

    @property
    def next_protocol(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Lists of string as ALPN values."""

    @property
    def pinned_peer_certificate_chain_sha256(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """@Document Some certificate chain sha256 hashes.
        @Document After normal validation or allow_insecure, if the server's cert chain hash does not match any of these values, the connection will be aborted.
        @Critical
        """

    @property
    def pinned_peer_certificate_public_key_sha256(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """@Document Some certificate public key sha256 hashes.
        @Document After normal validation (required), if one of certs in verified chain matches one of these values, the connection will be eventually accepted.
        @Critical
        """

    @property
    def curve_preferences(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Lists of string as CurvePreferences values."""

    @property
    def verify_peer_cert_in_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """@Document Replaces server_name to verify the peer cert.
        @Document After allow_insecure (automatically), if the server's cert can't be verified by any of these names, pinned_peer_certificate_chain_sha256 will be tried.
        @Critical
        """

    @property
    def ech_socket_settings(self) -> transport.internet.config_pb2.SocketConfig: ...
    def __init__(
        self,
        *,
        allow_insecure: builtins.bool = ...,
        certificate: collections.abc.Iterable[global___Certificate] | None = ...,
        server_name: builtins.str = ...,
        next_protocol: collections.abc.Iterable[builtins.str] | None = ...,
        enable_session_resumption: builtins.bool = ...,
        disable_system_root: builtins.bool = ...,
        min_version: builtins.str = ...,
        max_version: builtins.str = ...,
        cipher_suites: builtins.str = ...,
        fingerprint: builtins.str = ...,
        reject_unknown_sni: builtins.bool = ...,
        pinned_peer_certificate_chain_sha256: collections.abc.Iterable[builtins.bytes] | None = ...,
        pinned_peer_certificate_public_key_sha256: collections.abc.Iterable[builtins.bytes] | None = ...,
        master_key_log: builtins.str = ...,
        curve_preferences: collections.abc.Iterable[builtins.str] | None = ...,
        verify_peer_cert_in_names: collections.abc.Iterable[builtins.str] | None = ...,
        ech_server_keys: builtins.bytes = ...,
        ech_config_list: builtins.str = ...,
        ech_force_query: builtins.str = ...,
        ech_socket_settings: transport.internet.config_pb2.SocketConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ech_socket_settings", b"ech_socket_settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["allow_insecure", b"allow_insecure", "certificate", b"certificate", "cipher_suites", b"cipher_suites", "curve_preferences", b"curve_preferences", "disable_system_root", b"disable_system_root", "ech_config_list", b"ech_config_list", "ech_force_query", b"ech_force_query", "ech_server_keys", b"ech_server_keys", "ech_socket_settings", b"ech_socket_settings", "enable_session_resumption", b"enable_session_resumption", "fingerprint", b"fingerprint", "master_key_log", b"master_key_log", "max_version", b"max_version", "min_version", b"min_version", "next_protocol", b"next_protocol", "pinned_peer_certificate_chain_sha256", b"pinned_peer_certificate_chain_sha256", "pinned_peer_certificate_public_key_sha256", b"pinned_peer_certificate_public_key_sha256", "reject_unknown_sni", b"reject_unknown_sni", "server_name", b"server_name", "verify_peer_cert_in_names", b"verify_peer_cert_in_names"]) -> None: ...

global___Config = Config
